### ISSUE TITLE
提示插件结构不完整啊

### ISSUE THREAD

**Issue by jasonham** [taxigps/xbmc-addons-chinese#108]
提示插件结构不完整啊
是直接下载zip文件安装的
Launch XBMC
Navigate to System | Settings | Add-ons
Select Install from zip file
Browse to the directory where the new downloaded zip file is being stored.
Select OK

**Comment by taxigps** [comment]
请认真阅读 README.md 。你是否下载了正确的安装包。

**Comment by jasonham** [comment]
en my bad
