### ISSUE TITLE
[metadata.doubantv.com] 无法把信息显示在“剧集”里

### ISSUE THREAD

**Issue by trlsmax** [taxigps/xbmc-addons-chinese#109]
用的是libreelec 7.0.1MR版，里面的kodi是16.1，发现有如下问题：
1.部分剧集可以获得简介封面等信息，但无法在kodi的“剧集”里显示，在视频，文件里可以，例如搜索记录片《故宫》，《敦煌》
2.更新信息后，默认显示上一次使用的封面
3.更新信息后，在信息里点浏览，列表是空的
4.更新信息后，有时会删除上次更新的剧在“剧集”里的显示，不如我先更新后《西游记》，已经可以在KODI的“剧集”里看到，然后七视频-》文件里更新《故宫》，能正常获得信息封面，但信息页里的浏览是空的，回到KODI的“剧集”里，《西游记》就不见了

**Comment by taxigps** [comment]
升级1.2.1
