### ISSUE TITLE
英文键盘Chinese add-on

### ISSUE THREAD

**Issue by altarmobile** [taxigps/xbmc-addons-chinese#118]

**Comment by altarmobile** [comment]
您维护的chinese add-on 很好用。但是，所有的add－on都默认中文键盘layout。在某些情况下（如用手机遥控输入汉字），中文键盘layout就不能用。但是默认的English QWERTY则可以。您能在Chinese add－on的总设置中选择英语键盘吗？我使用英语作为默认系统。

**Comment by taxigps** [comment]
升级搜狐视频(SoHu)插件到2.4.8，增加选择Kodi内置键盘的设置项。其他看还有哪个插件需要增加设置？
