### ISSUE TITLE
Bilibili（0.27）最近又有些不能看了！

### ISSUE THREAD

**Issue by pockem** [taxigps/xbmc-addons-chinese#121]
@jiangming1399 
大师您好，百忙之中打扰了！
请您帮忙看看是什么问题，画质好的好像都打不开了，我联想到最近B站大会员政策（1080P）更新，可能和这个有关。
谢谢！

**Comment by jiangming1399** [comment]
请给出测试AV号

**Comment by pockem** [comment]
....因为最近没在用嘛 前一段时间好像是能放一些 我刚刚试了下好像什么都不能放了 就是转个圈然后就没了 也没有提示错误 不知道为什么。。 电脑和机顶盒都是这样。
