### ISSUE TITLE
kodi 17无法登录百度云

### ISSUE THREAD

**Issue by linesight** [taxigps/xbmc-addons-chinese#147]
填了用户名 密码之后，出现填验证码的窗口，但是窗口的输入框根本看不清，递交按钮也看不到，导致无法登录

**Comment by caasiu** [comment]
kodi.log有没有显示错误？

**Comment by linesight** [comment]
[kodi.log.txt](https://github.com/taxigps/xbmc-addons-chinese/files/778467/kodi.log.txt)
上面是Kodi.log，里面有python exception

我最开始在android tv发现百度云登录不了，后来在win7的虚拟机再试了下，同样不行，下面的是截图
![kodi_baiduyun](https://cloud.githubusercontent.com/assets/14064208/22996781/cba12b0c-f384-11e6-9174-ee5a1c21f07c.png)

**Comment by taxigps** [comment]
我在win10下用kodi17测试没有问题。不过`输入验证码`和`刷新验证码`两个按钮焦点用方向键无法切换，造成只能用鼠标点`刷新验证码`，遥控器用户不方便使用。@caasiu

**Comment by taxigps** [comment]
另：Kodi 16及更新版本内置软键盘已支持中文输入。

**Comment by linesight** [comment]
@taxigps  你点了“输入验证码”按钮然后有弹窗出来让你输入吗？ 我的kodi 17直接就报错了

**Comment by taxigps** [comment]
我上面测试时使用的mq7皮肤，回到默认皮肤estuary测试确实出错。ChineseKeyboard插件目前与这个皮肤不兼容。在Kodi本身已支持中文输入的情况下，是否应该不再使用ChineseKeyboard插件了？@caaisu

**Comment by caasiu** [comment]
@taxigps，谢谢。我会尽快把ChineseKeyboard插件移除。
另外， 对于输入验证码输入的问题，我现在的做法是新开一个window去显示，你们有没有更好的办法？

**Comment by taxigps** [comment]
@caasiu 当然得新开一个窗口显示。稍微修改下代码即可，设置button控件的`controlLeft`之类属性。见下面的代码。稍稍加长button钮，并设置alignment，确保按钮标签显示位置正确。
```
        self.image = xbmcgui.ControlImage(80, 100, 500, 200, self.vcode_path)
        self.buttonInput = xbmcgui.ControlButton(100, 330, 220, 50, label=u'输入验证码', alignment=6, font='font13', textColor='0xFFFFFFFF')
        self.buttonRefresh = xbmcgui.ControlButton(290, 330, 220, 50, label=u'刷新验证码', alignment=6, font='font13', textColor='0xFFFFFFFF')
        self.addControls([self.image, self.buttonInput, self.buttonRefresh])
        self.buttonInput.controlRight(self.buttonRefresh)
        self.buttonRefresh.controlLeft(self.buttonInput)
```

**Comment by caasiu** [comment]
百度云插件已经更新，谢谢@taxigps、@linesight
