### ISSUE TITLE
bilibili "enter AV code" not working

### ISSUE THREAD

**Issue by srett** [taxigps/xbmc-addons-chinese#151]
When selecting the menu entry to enter an AV code for a video, I get an error saying I should see the log file for additional details.

[errors.txt](https://github.com/taxigps/xbmc-addons-chinese/files/842516/errors.txt)

I'm running Kodi 17.0 (LibreELEC)

**Comment by taxigps** [comment]
update to  0.2.9.  add setting to select kodi internal keyboard by default to fix the issue:
Chinese keyboard plug-in not compatible with default skin of kodi 17.

**Comment by srett** [comment]
Confirmed working. Thanks a lot!
