### ISSUE TITLE
树莓派3B官方kodi上插件库无法运行

### ISSUE THREAD

**Issue by samuelchen** [taxigps/xbmc-addons-chinese#159]
能看到界面，但是“运行”和“设置”按钮是灰色的。
另外，单独下载视频插件，用kodi安装报错说插件包格式不对。

Kodi 17.1  Git: 20170401-7804a92-dirty

**Comment by samuelchen** [comment]
solved

**Comment by taxigps** [comment]
没用过树莓派。怎么解决的？分享一下吧

**Comment by samuelchen** [comment]
方法错了，之前用的是kodi安装插件，应该用中文插件管理来安装。
