### ISSUE TITLE
CNTV is not working

### ISSUE THREAD

**Issue by tq010or** [taxigps/xbmc-addons-chinese#16]
I am in Australia. The CNTV live used to work well, but it cannot find the stream now. 
I am using Raspberry PI B with Kodi.

**Comment by RunasSudo** [comment]
I have fixed this over at https://github.com/RunasSudo/plugin.video.cntv-live. I'm submitting it to this repo now.

**Comment by RunasSudo** [comment]
Unfortunately, the new version loads all video from Chinese servers, so watching from Australia may be slow. I'll look into finding an Australian server for the videos.

**Comment by tq010or** [comment]
Thanks for your quick update!

I upgraded to the new plugin, but only CCTV1 is working (and the signal
drops out some time later). All other channels are not working.
Either reports "no HLS stream" or "channel information unavailable".

Bo HAN
Postdoctoral Researcher
IBM Research Australia
Level 5/204 Lygon Street, Carlton, VIC 3053
Ph: +61 3 99213878
Email: bohan.ibm@au1.ibm.com

"Three passions, simple but overwhelmingly strong, have governed my life:
the longing for love, the search for knowledge, and unbearable pity for the
suffering of mankind." Bertrand Russell

**Comment by RunasSudo** [comment]
@tq010or I've made a few adjustments to the addon to fix those issues, available in 2.0.6.

**Comment by tq010or** [comment]
Thanks @RunasSudo

**Comment by Bennykoh** [comment]
Hi RunasSudo , 
I find out most of the china Live Tv are not working . I love your repo too bad  now i can only watch 3 channel only I hope you can update it soon.. ok dude thank alots for the sharing.

**Comment by onciao** [comment]
Hi Runas Sudo,
I am in Italy and all the China Live are not working too. My daughter was used to wathc CCTV 14 which is an amazing chinese cartoon channel. Please can you do something to let work CNTV on Kodi. I use an android system to watch it. Thanks in advance for everything you will do.

**Comment by RunasSudo** [comment]
Hi, thanks for reporting this. I'll look into it and see if I can publish a fix.

**Comment by bellcomm** [comment]
I'm using it in Malaysia. Only few channels are working. Others
either reports "no HLS stream" or "channel unavailable"

**Comment by sczhengyabin** [comment]
Strange，CNTV Live works well on win10 UWP kodi v17.0，but not works well on RPi3 with either Raspbian(kodi v15.2) or OSMC (kodi v16.1)
