### ISSUE TITLE
 SUBHD 字幕报错

### ISSUE THREAD

**Issue by sonicviking** [taxigps/xbmc-addons-chinese#164]
android 6.0 电视 kodi 17.1 在sub hd上的一些字幕能下载，一些不能下载，显示下载失败。具体log上的记录见图

![20170525124444](https://cloud.githubusercontent.com/assets/4038338/26436394/c9a3c280-4148-11e7-8b82-6477bc1e3b75.jpg)

**Comment by snailless** [comment]
这个日志并不是下载失败的根源，其实，这个“warning”在zimuku插件里也有，是写代码的时候，beautifulSoup的使用问题，和下载失败一点儿关系也没有。所以，请提供更多debug log。
