### ISSUE TITLE
要是能跟you-get项目结合起来就好了

### ISSUE THREAD

**Issue by 0312birdzhang** [taxigps/xbmc-addons-chinese#165]
这样一方面可以去广告，一方面可以方便解析视频地址，不过刚接触kodi，插件看上去都是独立的，不知道用you-get之后好不好做

**Comment by catro** [comment]
you-get 是用python3写的，kodi目前还不支持python3，所以会比较麻烦

**Comment by jindaxia** [comment]
恩，YKDL 支持py2和3

**Comment by taxigps** [comment]
kodi 官方插件库已包含script.module.youtube.dl，可以研究下调用它获取视频地址。

**Comment by suconghou** [comment]
个人觉得数据抓取与分析应该交由集中的服务器处理,客户端可以更专注于UI体验和播放. 这样更加高效且便于更新.

**Comment by jindaxia** [comment]
有个东西叫CDN，@suconghou

**Comment by jindaxia** [comment]
script.module.youtube.dl 还可以，就是国内站点不多 而且国内站点更新太慢

**Comment by suconghou** [comment]
@jindaxia 我是说视频地址解析和播放列表这些应该独立出来,后端来完成,减小客户端复杂度,客户端只需要调接口播放,和CDN没有关系.

**Comment by jindaxia** [comment]
恩，搞一个独立的插件来解析播放

**Comment by 0312birdzhang** [comment]
这个关了吧，感觉暂时也实现不了
