### ISSUE TITLE
bilibili看不到啊，bilibili2登录界面也收不到验证码

### ISSUE THREAD

**Issue by carnivion** [taxigps/xbmc-addons-chinese#166]
请修复，谢谢

**Comment by catro** [comment]
bilibili2收到不验证码能截个图吗？

**Comment by carnivion** [comment]
你好！

没有截图，就是登录的地方，输入了账号（手机号）和密码，然后又显示一个输入界面，最上面一排提示输入验证码，而手机上什么都没有收到。

另外，bilibili插件里面输入av号，有的可以播放，但有很多都不能播放，插件已升级到0.2.9，输入是使用kodi内置键盘。

系统是raspberry pi + osmc。

2017年5月29日 下午5:20，"catro" <notifications@github.com>写道：

bilibili2收到不验证码能截个图吗？

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/taxigps/xbmc-addons-chinese/issues/166#issuecomment-304615181>,
or mute the thread

**Comment by catro** [comment]
我只维护bilibili2这个插件。验证码在遥控APP上是看不到的，填写验证码是自定义图形界面，只能在主机上显示。

**Comment by raidenii** [comment]
Android上的Kodi 16.1和FTMC都打不开验证码界面，Windows版就可以，这是怎么回事？

**Comment by raidenii** [comment]
测试了下Android版的17.1也有这个bug。可能是因为找不到临时文件夹放验证码图片？
`15:09:04.763 T:547133846592   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/']
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.bilibili2/addon.py", line 383, in <module>
                                                plugin.run()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 332, in run
                                                items = self._dispatch(self.request.path)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 306, in _dispatch
                                                listitems = view_func(**items)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.bilibili2/addon.py", line 277, in login
                                                filename = tempfile.gettempdir() + '/' + ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(10)) + '.jpg'
                                              File "/home/jenkins/workspace/Android-ARM64/tools/depends/xbmc-depends/aarch64-linux-android-android-21/lib/python2.7/tempfile.py", line 275, in gettempdir
                                              File "/home/jenkins/workspace/Android-ARM64/tools/depends/xbmc-depends/aarch64-linux-android-android-21/lib/python2.7/tempfile.py", line 217, in _get_default_tempdir
                                            IOError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/']
                                            -->End of Python script error report<--
15:09:04.775 T:547381732416   DEBUG: ------ Window Init (DialogNotification.xml) ------`

**Comment by jindaxia** [comment]
@catro  用这个路径代替 tempfile 可以解决上面的问题
f = xbmcvfs.File("special://temp/aaa.jpg")

**Comment by raidenii** [comment]
@jindaxia 我做了一个fork

**Comment by jindaxia** [comment]
@raidenii 你可以向 catro发PR啊

**Comment by raidenii** [comment]
@jindaxia 现在登录是能登录，但是android上视频打不开，log显示用curl抓视频mime的时候就403
但是pc上用kodi同样的插件就没问题，也是很迷

**Comment by jindaxia** [comment]
@raidenii KODI版本不一样吧？ 有个方法可以不抓mime，我找一下代码

**Comment by raidenii** [comment]
@jindaxia 试了电视盒子上的Kodi 16.1和FTMC 16.1，手机上Kodi 17.3都有这个问题
PC上是16.1

**Comment by jindaxia** [comment]
试一下 listitem.setMimeType("video/mp4")

**Comment by jindaxia** [comment]
设置过了之后 就不会去请求header了

**Comment by raidenii** [comment]
放到哪里？

**Comment by jindaxia** [comment]
有几个play的地方，写法不一样，这里可以这样改。
```python
items.append({
            'label': item['pagename'], 
            'path': plugin.url_for('play', cid = item['cid']),
            'mime': "video/mp4",
            'is_playable': True,
            })
```

**Comment by raidenii** [comment]
一样的错误。

`09:29:10.378 T:547350115392   DEBUG: [('User-agent', 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0')]
09:29:11.096 T:547350115392   DEBUG: Date: Thu, 15 Jun 2017 13:29:10 GMT
                                            Content-Type: application/xml; charset=utf-8
                                            Content-Length: 997
                                            Connection: close
                                            Cache-Control: no-cache
                                            Access-Control-Allow-Origin: http://www.bilibili.com
                                            Access-Control-Allow-Credentials: true
                                            Remote_addr: 98.114.18.210
                                            Zone_id: 4
                                            Server: swoole-http-server
                                            Expires: Thu, 15 Jun 2017 13:29:09 GMT
                                            X-SLB-Server: shd-core-slb-04
                                            X-Upstream: 172.18.30.205:12500
                                            X-TKID: 1497533350702231586899
                                            X-Cache: BYPASS from us-alieast-bgp-w-01.hdslb.com
09:29:11.108 T:547350115392    INFO: CPythonInvoker(5, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.bilibili2/addon.py): script successfully run
09:29:11.111 T:547313165376   DEBUG: Thread scriptobs 547313165376 terminating
09:29:11.112 T:547911894080    INFO: easy_aquire - Created session to http://ws.acgvideo.com
09:29:11.196 T:547350115392    INFO: Python script stopped
09:29:11.196 T:547350115392   DEBUG: Thread LanguageInvoker 547350115392 terminating
09:29:11.562 T:547911894080   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://ws.acgvideo.com/7/73/10091864-1.flv?wsTime=1497544150&platform=pc&wsSecret2=3fa6b7d77340ccc0281f3a89dd1aeff7&oi=1651643090&rate=1280|Referer=http://www.bilibili.com/
09:29:11.563 T:547911894080   DEBUG: CCurlFile::GetMimeType - http://ws.acgvideo.com/7/73/10091864-1.flv?wsTime=1497544150&platform=pc&wsSecret2=3fa6b7d77340ccc0281f3a89dd1aeff7&oi=1651643090&rate=1280|Referer=http://www.bilibili.com/ -> failed
09:29:11.599 T:547911894080   DEBUG: Loading settings for http://ws.acgvideo.com/7/73/10091864-1.flv?wsTime=1497544150&platform=pc&wsSecret2=3fa6b7d77340ccc0281f3a89dd1aeff7&oi=1651643090&rate=1280|Referer=http://www.bilibili.com/
09:29:11.633 T:547911894080   DEBUG: CPlayerCoreFactory::GetPlayers(http://ws.acgvideo.com/7/73/10091864-1.flv?wsTime=1497544150&platform=pc&wsSecret2=3fa6b7d77340ccc0281f3a89dd1aeff7&oi=1651643090&rate=1280|Referer=http://www.bilibili.com/)`

**Comment by jindaxia** [comment]
上面的代码不对的。 这个问题 我以前碰到过，不知道什么原因，还是要用 原生的 xbmcgui.listitem.SetMimetype

**Comment by raidenii** [comment]
但是一样的代码在pc上就完全没问题，也是奇怪

**Comment by jindaxia** [comment]
现在怀疑是Curl库不一致的原因

**Comment by jindaxia** [comment]
返回item的时候 用这个
```python
listitem = xbmcgui.ListItem(title)
listitem.setInfo('video', {'Title': title})
listitem.setPath(path)
listitem.setProperty("mimetype", "video/mp4")
```

**Comment by jindaxia** [comment]
或者setMimeType('video/mp4')

**Comment by raidenii** [comment]
可能不是这个的问题……不过我不确定我改对没有
```
@plugin.route('/list_video/<aid>/')
def list_video(aid):
    plugin.set_content('videos')
    result = bilibili.get_av_list(aid)
    items = []
    for item in result:
    #    items.append({
    #        'label': item['pagename'], 
    #        'path': plugin.url_for('play', cid = item['cid']),
    #        'is_playable': True,
    #        })
		listitem = xbmcgui.ListItem(item['pagename'])
		listitem.setInfo('video',{'Title': item['pagename']})
		listitem.setPath(plugin.url_for('play', cid = item['cid']))
		listitem.setMimeType('video/mp4')
    return items
```

**Comment by jindaxia** [comment]
你没把listitem加到items结果里面去啊

**Comment by raidenii** [comment]
我傻逼了……
```
@plugin.route('/list_video/<aid>/')
def list_video(aid):
    plugin.set_content('videos')
    result = bilibili.get_av_list(aid)
    items = []
    for item in result:
		listitem = xbmcgui.ListItem('video')
		listitem.set_label(item['pagename'])
		listitem.set_path(plugin.url_for('play', cid = item['cid']))
		listitem.set_is_playable(True)
        #items.append({
            #'label': item['pagename'], 
            #'path': plugin.url_for('play', cid = item['cid']),
            #'is_playable': True,
            #})
		items.append(listitem)
    return items
```
但是错误还是一样

**Comment by raidenii** [comment]
我傻逼了
不过还是一样的错误
```
@plugin.route('/list_video/<aid>/')
def list_video(aid):
    plugin.set_content('videos')
    result = bilibili.get_av_list(aid)
    items = []
    for item in result:
		listitem = xbmcgui.ListItem('video')
		listitem.set_label(item['pagename'])
		listitem.set_path(plugin.url_for('play', cid = item['cid']))
		listitem.set_is_playable(True)
		listitem.setMimeType('video/mp4')
        #items.append({
            #'label': item['pagename'], 
            #'path': plugin.url_for('play', cid = item['cid']),
            #'is_playable': True,
            #})
		items.append(listitem)
    return items
```

**Comment by catro** [comment]
不好意思，最近比较忙，没时间来维护插件

**Comment by catro** [comment]
修复已经提交了，谢谢！
