### ISSUE TITLE
douban movie 刮削器在KODI 17.3依赖失效

### ISSUE THREAD

**Issue by jindaxia** [taxigps/xbmc-addons-chinese#169]
可能是17改了新的刮削器API 或者版本号有关

**Comment by taxigps** [comment]
douban刮削器依赖的metadata.common.movieposterdb.com插件被从官方库移除了。只有取消这个依赖，不再提供从movieposterdb.com获取海报功能。

**Comment by taxigps** [comment]
已升级1.1.3，恢复正常安装。
