### ISSUE TITLE
shooter(fake) became assrt.net and doesn't work anymore

### ISSUE THREAD

**Issue by grandixximo** [taxigps/xbmc-addons-chinese#171]
shooter(fake) became assrt.net and doesn't work anymore, so we can't download the subs anymore!

**Comment by taxigps** [comment]
@fffonion

**Comment by fffonion** [comment]
I noticed that assrt.net has an API now, we could probably use that instead
of parsing html pages. I'll make a new pr next week : )

**Comment by grandixximo** [comment]
Thanks!

**Comment by fffonion** [comment]
@taxigps Since shooter.cn is almost not providing updated subtitles, do you think we should remove that part and only search api.assrt.net?

**Comment by fffonion** [comment]
@taxigps Since shooter.cn is almost not updating now, should we set default value of "subSourceAPI" to false so that we choose api.assrt.net as a priority?

**Comment by taxigps** [comment]
fixed, thanks @fffonion!
