### ISSUE TITLE
zimuzu字幕插件 无法搜索一些完整文件名作为搜索字符串

### ISSUE THREAD

**Issue by jindaxia** [taxigps/xbmc-addons-chinese#175]
例如，下面这样的字幕无法搜索到，必须简化到 King.Arthur.Legend.of.the.Sword 才能搜到

> King.Arthur.Legend.of.the.Sword.2017.1080p.KORSUB.HDRip.x264.AAC2.0-STUTTERSHIT.mp4

如果有时间 我可以来发一个PR 解决这个问题，思路是先用完整文件名搜，如果没有结果，就简化

**Comment by jindaxia** [comment]
再次调试 发现 King Arthur:Legend of the Sword 可以搜到，

**Comment by jindaxia** [comment]
第一步搜索 用这个 API 更好一点，识别高
http://www.zimuzu.tv/search/api?keyword=King%20Arthur%20Legend%20of%20the%20Sword

**Comment by taxigps** [comment]
字幕插件不是用完整文件名来搜索的，对于已通过scrape建立电影资料库项目的电影，是用OriginalTitle也就是英文片名搜索。对于未加入电影资料库的，会从文件名中分离出年代之前的片名来搜索。

**Comment by taxigps** [comment]
@xodidox 考虑下使用API？

**Comment by taxigps** [comment]
@jindaxia 看了下，那个api返回的json数据没有字幕信息啊。
