### ISSUE TITLE
dnvodplayer plugin无法拿到视频播放的url

### ISSUE THREAD

**Issue by renweizhukov** [taxigps/xbmc-addons-chinese#176]
将多瑙网址更新为dnvod.tv，也将搜索SessionId的key改为dn_sid，此时已能进行搜索并显示搜索结果和播放清单，但当点击播放某集时，无法得到播放视频的真正url。

获取该url的code如下：

```python
data = urllib.urlencode({'key':keyString})
requestSec = urllib2.Request(urlSec,data,headers2)
responseSec = urllib2.urlopen(requestSec)
real_url = responseSec.read()
```

此时urlSec和keyString的一个样本取值：

```python
urlSec = 'http://www.dnvod.tv/Movie/GetResource.ashx?id=UEYVWMvoPUQ%3d&type=htm'
keyString = '969dab8b44944d149e06be9043f516ad'
```

urlopen得到的real_url值为-2。

更新网址和SessionId key的change请见#177

**Comment by taxigps** [comment]
已升级1.0.3。感谢提交修正。

**Comment by renweizhukov** [comment]
@taxigps 不好意思，我可能在前面的描述中误导你了，我的commit并不能完全解决这个issue，只能是进行搜索并显示搜索结果和播放清单，但无法播放。原因就如上所述，没有得到播放视频的真正url。要不我更新一下这个issue的title，然后重新创建一个issue？谢谢！

**Comment by taxigps** [comment]
这个网站我访问不了，因此并未测试。有条件的朋友来修正吧。
