### ISSUE TITLE
failed to install zip file

### ISSUE THREAD

**Issue by liuxuan30** [taxigps/xbmc-addons-chinese#184]
Hi there,

I use kodi-20171024-b184048-yab-tvos.deb and installed on my ATV 4K. Then I download add on from https://github.com/taxigps/xbmc-addons-chinese, which is a chiese add on that includes chinese video sources. I launched a python http server, and add the source in kodi.

I click install from zip file and navigate to my http server source, I can see the zip file. However when I choose the zip file, kodi always said failed to install from zip file. But I can unzip this file on my mac, it looks normal. What's wrong? Thanks.

**Comment by uncletong** [comment]
you need to download this file  "repository.xbmc-addons-chinese-1.2.1.zip" in readme instead of download all codes and install it.

**Comment by liuxuan30** [comment]
yes I indeed downloaded `repository.xbmc-addons-chinese-1.2.1.zip` rather than the code and this is the file which failed to install.

**Comment by taxigps** [comment]
try to install zip file from smb share or local drive. may be use http server is the problem?

**Comment by liuxuan30** [comment]
why http server can be the problem? I remember other source is http as well?

**Comment by taxigps** [comment]
need log file to find the problem.
