### ISSUE TITLE
163字幕,和

### ISSUE THREAD

**Issue by wcg928** [taxigps/xbmc-addons-chinese#190]
163字幕和sub hd 字幕不能下载,提示" 字幕下载失败" 搜索可以搜到字幕

**Comment by 404user** [comment]
我的也是。。。。是不是作者停止更新了？

**Comment by taxigps** [comment]
163sub 升级至 1.0.6。
subhd 升级至 1.0.14。参见：https://github.com/taxigps/xbmc-addons-chinese/pull/196
