### ISSUE TITLE
在Xbian for raspberry上安裝會出現格式不符

### ISSUE THREAD

**Issue by seigtmh** [taxigps/xbmc-addons-chinese#192]
請教有先進曾經嘗試在Xbian上安裝過這個addon嗎?今天嘗試安裝時，一直出現格式不符，無法安裝，不知道有沒有解決的方法，感謝各位先進

**Comment by 0312birdzhang** [comment]
多试几次或者换个目录就好了。
我在小米盒子上一直这样，不知道是什么bug

**Comment by seigtmh** [comment]
感謝先進指導，那我先換個資料夾再多試幾次看看好了

**Comment by 0312birdzhang** [comment]
客气了，如果还是不行就看看是不是包还有二级目录。
由于是python，讲道理是跟平台无关的

**Comment by taxigps** [comment]
是否下载了正确的安装包，直接下载本项目源码压缩包是不行的。
