### ISSUE TITLE
douban movie 刮削器在KODI 17 版本无法同步电影演员啊

### ISSUE THREAD

**Issue by flashliao** [taxigps/xbmc-addons-chinese#193]
没人发现电影源同步，获取不到演员信息吗，上一个版本不能同步封面但是演员同步是正确的。这个版本能同步封面了，但是电影的演员提取不到，建议修复此bug。

**Comment by taxigps** [comment]
updated to v1.1.6

**Comment by flashliao** [comment]
实测用豆瓣刮削器，无法显示演员
![qq 20180129161005](https://user-images.githubusercontent.com/28710685/35499805-e39beee4-050e-11e8-9c5e-9f26ce8bd9f5.png)
![qq 20180129161110](https://user-images.githubusercontent.com/28710685/35499837-0affcc62-050f-11e8-91ab-d151e1800900.png)

**Comment by v2cn** [comment]
请教一下，现在的17.6版本，豆瓣收刮器v1.23, 在插件的分类是『剧集』，现在如果文件夹的属性是『电影』，就无法选择豆瓣，只能设定是『剧集』才可以选择。

**Comment by taxigps** [comment]
@v2cn 电影和剧集并非同一个刮削器。豆瓣电影刮削器从Kodi官方插件库安装。

**Comment by v2cn** [comment]
太感谢你回复！因为刚使用kodi，特意注册个账号上来问的。
谢谢!
