### ISSUE TITLE
我更新了subhd，如何申请更新

### ISSUE THREAD

**Issue by likeca** [taxigps/xbmc-addons-chinese#195]
以知问题：
1. 有些字幕受版权保护，不能下载，因此会下载出错
2. 如果过于频繁搜索及下载subhd会要求验证保护，而导致下载出错，解决办法用本机到subhd滑动验证。

**Comment by taxigps** [comment]
对插件的修改可在本项目提交pr

**Comment by taxigps** [comment]
已完成更新
