### ISSUE TITLE
zumuku和zimuzu的字幕下载失败

### ISSUE THREAD

**Issue by SelfEnough** [taxigps/xbmc-addons-chinese#197]
硬件环境：小米电视4A+Kodi17.4（最高只能装到这个版本17.5往上都是闪退）
扩展插件均为更新到最新版。

字幕库和字幕组两个字幕扩展都失效了
能够搜索到字幕，但是下载每次都提示下载失败
HD和伪射手没有问题
但是伪射手的字幕没有zimuku全，

**Comment by SelfEnough** [comment]
射手字幕也有个bug，下载的字幕会堆积，换一部电影后，下载了新的字幕后，选择字幕的时候，该片的字幕往往是在最底部的，上面全是之前下载过的字幕文件，并且累积到一定数量后，新下载的字幕不会出现在这个列表了，得去字幕缓存文件夹内清理些字幕。

**Comment by taxigps** [comment]
ZiMuZu插件升级1.0.3
