### ISSUE TITLE
kodi有新特性吗？

### ISSUE THREAD

**Issue by osfans** [taxigps/xbmc-addons-chinese#20]
kodi14已经进archlinux的软件库了。
我们要区分xbmc13和kodi14吗？
加新特性前搞个xbmc的分支？master留给kodi？

**Comment by RunasSudo** [comment]
According to the Wiki, [‘Most things from v13 will work in v14.’](http://kodi.wiki/view/Kodi_v14_%28Helix%29_FAQ#What_might_break_when_upgrading_to_v14.3F_.28add-ons.2C_skins.2C_remotes.2C_etc.29)

**Comment by osfans** [comment]
@RunasSudo 目前我只看到版本号的差异，具体有什么改进看来还要研究下。
http://kodi.wiki/view/Addon.xml#Dependency_versions

XBMC version | xbmc.python | xbmc.gui | xbmc.json | xbmc.metadata | xbmc.addon
----- | ----- | ----- | ----- | ----- | -----
Gotham 13.x 	|2.14.0 |	5.0.1 |	6.6.0 |	2.1.0 |	13.0.0
Kodi 14.x 	|2.19.0 |	5.3.0 |	6.20.0 |	2.1.0 |	14.0.0

**Comment by taxigps** [comment]
搞不同版本的库太麻烦，暂时还是就集中一个库吧，用了新版本的特性插件，在低版本里显示不兼容插件就行了。

**Comment by osfans** [comment]
好的。那就暂时先不加新的了。
