### ISSUE TITLE
树莓派下Kodi17.6版本，iptv能够显示电视信息，但是点击播放的时候，一直在转圈，没有画面信息出来

### ISSUE THREAD

**Issue by andyshi2008** [taxigps/xbmc-addons-chinese#200]
RT，可能是什么原因？网络是100M的，速度没问题，小米盒子的直播都很正常。谢谢

**Comment by 123xiao** [comment]
遇到了同样的问题，ubuntu的也是这样的情况

**Comment by 123xiao** [comment]
目测是直播源已经失效了

**Comment by taxigps** [comment]
自己找可用的直播源修改下channel.m3u文件中的直播地址吧。

**Comment by andyshi2008** [comment]
找了，北邮的直播源，还是不行，直接用网页看巨快~~

**Comment by xhanglizhu** [comment]
你们都在哪里找的直播源？

**Comment by lurui45** [comment]
有长期有效的直播源吗？我感觉这些直播源动不动就失效，换来换取 很蛋疼呢

**Comment by yangxuan8282** [comment]
@taxigps 问下找到可用直播源后怎么修改 channel.m3u 呢，通过 smb 访问树莓派没找到这个文件，然后尝试把插件 zip 里的文件修改然后重新打包，但是从本地安装会提示安装失败
