### ISSUE TITLE
zms 字幕不能下載 | zms subtitle can't download

### ISSUE THREAD

**Issue by ssbrianhk** [taxigps/xbmc-addons-chinese#205]
ZMS 字幕插件可以搜尋到字幕，但每次按下載都失敗，請幫忙修正，謝謝。
zms subtitle plugin can search but can't download, please help to fix it, thanks a lot.

**Comment by taxigps** [comment]
升级1.0.1

**Comment by ssbrianhk** [comment]
After updated to 1.0.1 still can't download, always show a cancel button only.
