### ISSUE TITLE
add-on repo与add-on lib的翻译

### ISSUE THREAD

**Issue by osfans** [taxigps/xbmc-addons-chinese#21]
两者都翻译成了插件库。
我去transifex看了，发现是@taxigps 老大翻译的。

要不repo翻译成“仓库”、“源”或者“软件库”？

**Comment by taxigps** [comment]
是应该区分一下。或者把add-on lib改为插件模块？

**Comment by osfans** [comment]
也可以。反正就要区分一下。

现在就是中文界面点击 ```插件->获取插件->Chinese Add-ons```时，菜单出现两个插件库：
- Chinese Add-ons属于Add-on repository
- Chinese keyboard属于Add-on libraries
- 其他几项是：字幕、程序插件、视频插件、音乐插件。

**Comment by taxigps** [comment]
已将add-on lib改为插件模块。
