### ISSUE TITLE
youku经常出现地址解析错误

### ISSUE THREAD

**Issue by shootheart** [taxigps/xbmc-addons-chinese#211]
提示需要重新登录，我把插件先禁用再启用之后还是不能播放，不知道有没有解决方法。

**Comment by taxigps** [comment]
已升级插件至2.2.10，更新ccode参数。这个参数网站会不定期调整，本人不使用视频插件，不能保证及时更新，如再有变动，你可以参照此地址的ccode修行修改插件代码：https://github.com/soimort/you-get/blob/develop/src/you_get/extractors/youku.py
