### ISSUE TITLE
Failed to download subtitles

### ISSUE THREAD

**Issue by risingson05** [taxigps/xbmc-addons-chinese#213]
Every subtitle from SubHD says "failed to download subtitles". Downloads from other subtitle services have no problem.

I've tried:
- Uninstalling and re-installing SubHD
- Restarting OSMC and rPi
- Setting permissions on video source to read/write for all users
- Tried enabling guest account on NAS

Setup Info:
- Raspberry Pi 3 B
- OSMC Kodi 17.6
- SubHD 1.0.15 (downloaded from Chinese Add-Ons and SuperRepo - both have same problem)
- Subtitle settings: store next to video
- Video source: NFS to Synology NAS (NFS permissions set to read/write for all users mapped to admin from rPI IP address)

**Comment by RadioDisney** [comment]
我的也是同样问题，android 7.0，kodi 17.6，SONY 65S8500C，Sub HD 1.0.15，可以找到字幕列表，但是任何一个字幕都是下载失败

**Comment by taxigps** [comment]
该网站获取下载链接需进行图形验证，插件无法实现。不再升级该插件。

**Comment by pizzamx** [comment]
> 该网站获取下载链接需进行图形验证，插件无法实现。不再升级该插件。

哭了哭了

**Comment by taxigps** [comment]
升级1.0.16
