### ISSUE TITLE
rar格式的字幕文件包里面的字幕文件无法浏览

### ISSUE THREAD

**Issue by megaslx** [taxigps/xbmc-addons-chinese#214]
从字幕库或者字幕组下的压缩文件包只要是rar格式的就大概率打开以后是空的，一个字幕文件都列不出来。不知道这个有办法搞吗？

**Comment by sylar605** [comment]
同 平台 XBOXONE

**Comment by megaslx** [comment]
字幕库有验证码了，没办法自动下载了







在2018年12月31 00时50分, "Sylar"<notifications@github.com>写道:



同 平台 XBOXONE

**Comment by sylar605** [comment]
> 
> 字幕库有验证码了，没办法自动下载了 在2018年12月31 00时50分, "Sylar"<notifications@github.com>写道: 同 平台 XBOXONE — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

zimuku试了下没有验证码呀

**Comment by ilbefun** [comment]
subhd也是大部分字幕能下载但是无法打开，从pc浏览器看，大多是rar的字幕，求大佬解决

**Comment by taxigps** [comment]
升级最新kodi 18.6，升级vs.rar插件到2.3.0。已解决rar支持不完善问题
