### ISSUE TITLE
CNTV 無畫面只有聲音

### ISSUE THREAD

**Issue by kirajhpang** [taxigps/xbmc-addons-chinese#215]
Hi, I load your repo, and load CNTV plugin, but I only able to get result like this. 

All channels only have sound without proper image. Is that anything wrong?

![image](https://user-images.githubusercontent.com/8136063/49680945-612b3600-fad5-11e8-81e5-baf373820b46.png)

**Comment by wangerzi** [comment]
同样问题，我还以为我盒子出问题了，然后改用 5video 了
