### ISSUE TITLE
Is this addon still active?

### ISSUE THREAD

**Issue by michaelbr51** [taxigps/xbmc-addons-chinese#223]
Hi, I'm new to this addon, added it but when I tried to access the channels, got errors, am I doing something wrong? The zip file is 2 years old, so not sure if I'm using the right file.

**Comment by czb0088** [comment]
这个插件我也无法安装，百度找到kodi网站https://forum.kodi.tv/showthread.php?tid=64250 这里有个新的插件repository.xbmc-addons-chinese-1.2.1.zip，我根据说明下载这个zip安装上去了，但是里面所有的youku，pps，乐视、CCTN的插件安装了，但是都不能播放。不知道大家是不是这样。

**Comment by ailionx** [comment]
@czb0088 我也是这样，竟然没有一个能用...
