### ISSUE TITLE
zimuku和zimushe大量字幕内容为空

### ISSUE THREAD

**Issue by asinitial** [taxigps/xbmc-addons-chinese#224]
平台：
1. Debian buster + Kodi 17.6
2. Android + Kodi 18

zimuku版本1.0.10
zimushe版本1.0.3

如《毒枭：墨西哥》E04、《纸牌物》S06E04

Log(Debian + Kodi 17.6):
00:08:40.106 T:139804097173248  NOTICE: metahandler: Initializing MetaHandlers version: 3.0.3
00:08:40.111 T:139804097173248  NOTICE: metahandler: Loading sqlite3 as DB engine version: 3.26.0
00:08:40.112 T:139804097173248  NOTICE: metahandler: No SQLite rows requiring update
00:08:40.643 T:139803131639552 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
00:08:57.978 T:139802427569920   ERROR: Remove - Error removing /home/allen/.kodi/userdata/addon_data/service.subtitles.zimuku/temp/__MACOSX
00:08:57.978 T:139802427569920   ERROR: Remove - Error removing /home/allen/.kodi/userdata/addon_data/service.subtitles.zimuku/temp
00:09:17.146 T:139805532566272   ERROR: Extract, No archive given
00:09:18.531 T:139802427569920   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/allen/.kodi/addons/service.subtitles.zimuku/service.py", line 264, in <module>
                                                subs = Download(params["link"], params["lang"])
                                              File "/home/allen/.kodi/addons/service.subtitles.zimuku/service.py", line 196, in Download
                                                subtitle_list.append(os.path.join(path, list[sel]))
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
00:09:18.562 T:139804131268352   ERROR: GetDirectory - Error getting plugin://service.subtitles.zimuku/?action=download&link=http://www.zimuku.cn/detail/111573.html&lang=['/xe7/xae/x80/xe4/xbd/x93/xe4/xb8/xad/xe6/x96/x87/xe5/xad/x97/xe5/xb9/x95', '/xe7/xb9/x81/xe9/xab/x94/xe4/xb8/xad/xe6/x96/x87/xe5/xad/x97/xe5/xb9/x95', 'English/xe5/xad/x97/xe5/xb9/x95', '/xe5/x8f/x8c/xe8/xaf/xad/xe5/xad/x97/xe5/xb9/x95']
00:09:21.426 T:139802427569920   ERROR: Remove - Error removing /home/allen/.kodi/userdata/addon_data/service.subtitles.zimuku/temp/__MACOSX
00:09:21.426 T:139802427569920   ERROR: Remove - Error removing /home/allen/.kodi/userdata/addon_data/service.subtitles.zimuku/temp
00:09:38.108 T:139802427569920   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/allen/.kodi/addons/service.subtitles.zimuku/service.py", line 264, in <module>
                                                subs = Download(params["link"], params["lang"])
                                              File "/home/allen/.kodi/addons/service.subtitles.zimuku/service.py", line 196, in Download
                                                subtitle_list.append(os.path.join(path, list[sel]))
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
00:09:38.163 T:139804131268352   ERROR: GetDirectory - Error getting plugin://service.subtitles.zimuku/?action=download&link=http://www.zimuku.cn/detail/111093.html&lang=['/xe7/xae/x80/xe4/xbd/x93/xe4/xb8/xad/xe6/x96/x87/xe5/xad/x97/xe5/xb9/x95', '/xe7/xb9/x81/xe9/xab/x94/xe4/xb8/xad/xe6/x96/x87/xe5/xad/x97/xe5/xb9/x95', 'English/xe5/xad/x97/xe5/xb9/x95', '/xe5/x8f/x8c/xe8/xaf/xad/xe5/xad/x97/xe5/xb9/x95']
00:09:43.031 T:139802427569920   ERROR: Remove - Error removing /home/allen/.kodi/userdata/addon_data/service.subtitles.zimuku/temp/__MACOSX
00:09:43.032 T:139802427569920   ERROR: Remove - Error removing /home/allen/.kodi/userdata/addon_data/service.subtitles.zimuku/temp
00:09:54.648 T:139805532566272   ERROR: Extract, No archive given
00:09:56.116 T:139802427569920   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/allen/.kodi/addons/service.subtitles.zimuku/service.py", line 264, in <module>
                                                subs = Download(params["link"], params["lang"])
                                              File "/home/allen/.kodi/addons/service.subtitles.zimuku/service.py", line 196, in Download
                                                subtitle_list.append(os.path.join(path, list[sel]))
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
00:09:56.157 T:139804131268352   ERROR: GetDirectory - Error getting plugin://service.subtitles.zimuku/?action=download&link=http://www.zimuku.cn/detail/111168.html&lang=['/xe7/xae/x80/xe4/xbd/x93/xe4/xb8/xad/xe6/x96/x87/xe5/xad/x97/xe5/xb9/x95', '/xe7/xb9/x81/xe9/xab/x94/xe4/xb8/xad/xe6/x96/x87/xe5/xad/x97/xe5/xb9/x95', 'English/xe5/xad/x97/xe5/xb9/x95', '/xe5/x8f/x8c/xe8/xaf/xad/xe5/xad/x97/xe5/xb9/x95']
00:10:14.157 T:139805532566272   ERROR: Extract, No archive given
00:10:15.609 T:139802427569920   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/allen/.kodi/addons/service.subtitles.zimushe/service.py", line 269, in <module>
                                                subs = Download(params["link"], params["lang"])
                                              File "/home/allen/.kodi/addons/service.subtitles.zimushe/service.py", line 201, in Download
                                                subtitle_list.append(os.path.join(path, list[sel]))
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
00:10:15.647 T:139805524145920   ERROR: GetDirectory - Error getting plugin://service.subtitles.zimushe/?action=download&link=https://www.zimushe.com/s_333kqbzgaca3/&lang=['/xe7/xae/x80/xe4/xbd/x93', 'ASS', 'SRT']
00:10:48.658 T:139802427569920   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/allen/.kodi/addons/service.subtitles.zimushe/service.py", line 269, in <module>
                                                subs = Download(params["link"], params["lang"])
                                              File "/home/allen/.kodi/addons/service.subtitles.zimushe/service.py", line 201, in Download
                                                subtitle_list.append(os.path.join(path, list[sel]))
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
00:10:48.704 T:139805524145920   ERROR: GetDirectory - Error getting plugin://service.subtitles.zimushe/?action=download&link=https://www.zimushe.com/s_66siqphzzfb6/&lang=['/xe7/xae/x80/xe4/xbd/x93', '/xe7/xb9/x81/xe9/xab/x94', 'English', '/xe5/x8f/x8c/xe8/xaf/xad', 'ASS', 'SRT']
00:11:14.483 T:139805532566272  NOTICE: CVideoPlayer::CloseFile()
00:11:14.483 T:139805532566272  NOTICE: VideoPlayer: waiting for threads to exit
00:11:14.486 T:139803332966144  NOTICE: CVideoPlayer::OnExit()

**Comment by taxigps** [comment]
手工删除目录/home/allen/.kodi/userdata/addon_data/service.subtitles.zimuku/temp再试下吧

**Comment by asinitial** [comment]
> 手工删除目录/home/allen/.kodi/userdata/addon_data/service.subtitles.zimuku/temp再试下吧

感谢回复。
经测试删除temp文件夹，包括升级至最新版，报错依旧。

Log:
21:26:59.472 T:139890170315520   ERROR: Extract, No archive given
21:27:02.441 T:139887075649280   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/allen/.kodi/addons/service.subtitles.zimuku/service.py", line 255, in <module>
                                                subs = Download(params["link"], params["lang"])
                                              File "/home/allen/.kodi/addons/service.subtitles.zimuku/service.py", line 187, in Download
                                                subtitle_list.append(os.path.join(path, list[sel]))
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
21:27:02.488 T:139888767923968   ERROR: GetDirectory - Error getting plugin://service.subtitles.zimuku/?action=download&link=http://www.zimuku.cn/detail/111573.html&lang=['/xe7/xae/x80/xe4/xbd/x93/xe4/xb8/xad/xe6/x96/x87/xe5/xad/x97/xe5/xb9/x95', '/xe7/xb9/x81/xe9/xab/x94/xe4/xb8/xad/xe6/x96/x87/xe5/xad/x97/xe5/xb9/x95', 'English/xe5/xad/x97/xe5/xb9/x95', '/xe5/x8f/x8c/xe8/xaf/xad/xe5/xad/x97/xe5/xb9/x95']

**Comment by asinitial** [comment]
Update:
找到一个临时的解决方法，比较麻烦。
先下一遍字幕，等报错后，找个文件管理器手动解压字幕，然后重新下刚才的字幕，就可以正常加载解压出来的字幕了。

**Comment by megaslx** [comment]
感觉本质就是kodi的rar支持有问题，这个问题困扰很久了

**Comment by asinitial** [comment]
Android TV平台，更新至最新版后，手动解压也不行了。经观察，重新下载字幕后，会清空temp文件夹中已解压的字幕文件（包括之前手动解压的），但依然无法自动解压并加载重新下载的压缩包（尤其是rar）

**Comment by taxigps** [comment]
kodi 17支持rar没问题。kodi 18取消了内置rar支持，改为安装vfs-rar虚拟文件系统插件，不过这个插件对中文支持有问题，会造成kodi崩溃。

**Comment by linxucc** [comment]
是否可以考虑用python的rar库把rar的处理独立出来？感觉vfs-rar靠不住啊。反馈问题很多。

**Comment by jindaxia** [comment]
没有纯python的rar库

**Comment by taxigps** [comment]
python的rar库只能获取压缩文件信息，解压得调用外部解压程序。还是等vfs.rar插件升级吧。

**Comment by texlahoma** [comment]
kodi 17.6 rar支持也有问题啊 zimuku subhd的rar字幕都解压不了

**Comment by taxigps** [comment]
升级最新kodi 18.6，升级vs.rar插件到2.3.0。已解决rar支持不完善问题。

**Comment by alanljj** [comment]
vfs.rar下载地址 https://kodi-addons.club/addon/vfs.rar/
