### ISSUE TITLE
Sub HD插件选择压缩包里的字幕时，列表乱码，无法判断是简体还是繁体，只能下载使用以后才能知道

### ISSUE THREAD

**Issue by 520ph** [taxigps/xbmc-addons-chinese#226]
平台： Android + Kodi 18
最新版 Sub HD 插件

我搜索电影：《海王》的字幕

![image](https://user-images.githubusercontent.com/18325087/54012779-18594b00-41b2-11e9-9ff5-168cee7a3817.png)
![image](https://user-images.githubusercontent.com/18325087/54012782-1c856880-41b2-11e9-9713-a216895b3ea6.png)
![image](https://user-images.githubusercontent.com/18325087/54012808-227b4980-41b2-11e9-8380-0cadd2dbe75d.png)

**Comment by taxigps** [comment]
我测试正常，不过用的kodi17

**Comment by king4leo** [comment]
同样的问题
而且其他电影下载字幕后选择压缩包中字幕时，显示总是海王的这个字幕压缩包而非实际下载的电影字幕压缩包

**Comment by omd66** [comment]
碰到了同样的问题，无论下载的是什么字幕，打开压缩包还是之前的字幕。

**Comment by 520ph** [comment]
感谢更新，不过乱码的问题好像依旧存在

**Comment by 520ph** [comment]
> 升级1.0.17

我字符集设置是默认的

**Comment by taxigps** [comment]
经查乱码不是字幕插件的问题，是kodi18的解压功能有问题，解压出的文件名就是乱码。

**Comment by 520ph** [comment]
好的，谢谢

**Comment by taxigps** [comment]
升级1.0.18版解决Kodi 18下zip包列表乱码问题。
