### ISSUE TITLE
douban tv 只能搜到第一季分集信息

### ISSUE THREAD

**Issue by v2cn** [taxigps/xbmc-addons-chinese#229]
豆瓣电视剧刮削器只能搜到第一季的分集信息，后续的季度搜到的是空目录。
搜了一遍帖子没发现有人提及到。请问是不是对剧集的命名格式有规范？
谢谢！

**Comment by iknowzxc** [comment]
一样的问题，我的目录结构是这样

权利的游戏
------Season 1
------Season 2
------Season 3

**Comment by iknowzxc** [comment]
今天又研究了一下，如果用豆瓣削刮器，不同季必须分开放，否则只能搜到第一季：
权利的游戏 Season1
权利的游戏 Season2
权利的游戏 Season3

如果用TMDB削刮器，可以把不同季放到一个文件夹下面：
权利的游戏
        |-----------Season1
        |-----------Season2
        |-----------Season2

**Comment by v2cn** [comment]
海报和内容介绍没问题。分集信息标题能搜刮到？

**Comment by iknowzxc** [comment]
> 海报和内容介绍没问题。分集信息标题能搜刮到？

这个没注意
