### ISSUE TITLE
插件好像大部分都不能用了

### ISSUE THREAD

**Issue by hewittchoi** [taxigps/xbmc-addons-chinese#230]

**Comment by svandex** [comment]
我也发现了，大多数都不能用了，优酷也是进去可以看到分类，但是没法播放视频

**Comment by malimaliao** [comment]
python for Kodi is a that often changes according to the target website. If the target website changes and the screen structure of the crawler changes, then lazy programmers will inevitably cause the invalidation of their work.

**Comment by holywen** [comment]
在主页readme.md中能否标注一下状态，这样大家知道哪些已经失效了。
