### ISSUE TITLE
Douban TV 提示无法连接远程服务器

### ISSUE THREAD

**Issue by Milokita** [taxigps/xbmc-addons-chinese#232]
在kodi 18.2 Leia 中进行扫描时提示无法连接远端服务器

**Comment by v2cn** [comment]
最近几天出现的，我这边也是，之前用盒子，现在用电脑端测试也一样。
豆瓣的电影刮削器也同样问题。

估计douban的API变了。

**Comment by sonicviking** [comment]
我也出现这个问题几天了

**Comment by taxigps** [comment]
好像是豆瓣API已经停止提供服务了。

**Comment by Milokita** [comment]
但愿会API会恢复服务， 如果不恢复发话有转而开发Mtimes的想法吗

**Comment by v2cn** [comment]
目前用TMDB对应的剧集刮削器代替了。支持中文内容，在插件设置一下就可以。
这个插件可以搜到多季度剧集的分集信息，也算是解决了之前douban tv的问题。

**Comment by Milokita** [comment]
电影你也是用的TMDB吗 我的扫描显示不能连接远端服务器

**Comment by v2cn** [comment]
电影我用时光网Mtime的插件。TMDB没测试过。

**Comment by Milokita** [comment]
嗯，谢谢回复




------------------ 原始邮件 ------------------
发件人: "v2cn"<notifications@github.com>; 
发送时间: 2019年5月29日(星期三) 晚上11:13
收件人: "taxigps/xbmc-addons-chinese"<xbmc-addons-chinese@noreply.github.com>; 
抄送: "XNG"<flipwing@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [taxigps/xbmc-addons-chinese] Douban TV 提示无法连接远程服务器 (#232)




电影我用时光网Mtime的插件。TMDB没测试过。
 
&mdash;

**Comment by v2cn** [comment]
你试试浏览器访问
https://www.themoviedb.org/
应该是可以正常访问的，影视资料都是从这个网站提供。

**Comment by neversleepnight** [comment]
豆瓣官网数据库还是在线的，但是估计有变化。这个api没有人更新了。求更新douban 合 doubantv

**Comment by ifurther** [comment]
從[這裡](https://blog.csdn.net/qq_37674858/article/details/100729102)看到好像需要apikey
