### ISSUE TITLE
Error when vsf.rar try to update subhd to latest version 

### ISSUE THREAD

**Issue by jameswccc** [taxigps/xbmc-addons-chinese#237]
Got below error when try to upgrade SUBHD to latest version, using kodi 17.6 ,android version
Thx

对vfs.rar版本2.0.7的依赖无法满足

**Comment by taxigps** [comment]
vfs.rar为针对18.0的，17.6可先不升级SUBHD插件，目前不影响使用

**Comment by jameswccc** [comment]
Thanks
