### ISSUE TITLE
assrt用api显示2000错误。

### ISSUE THREAD

**Issue by fireflycao** [taxigps/xbmc-addons-chinese#239]
前几天好好的，昨天开始出现的。借宝地问下，安卓的kodi有办法复制粘贴字符吗？

错误代码 | 错误信息 | 说明
-- | -- | --
20000 | your request is missing essential arguments | 请求缺少参数
20001 | invalid token | Token不存在
20400 | API endpoint not found | API终结点不存在
20900 | subtitle not found | 字幕不存在

**Comment by taxigps** [comment]
已加入支持Kodi 19的assrt.net字幕插件。
