### ISSUE TITLE
由于豆瓣关闭了API，能否考虑利用别人的API接口？

### ISSUE THREAD

**Issue by flashliao** [taxigps/xbmc-addons-chinese#240]
时光网的刮刮器我觉得没有豆瓣号，现在应该是关闭了开放的API接口，能否考虑使用其他第三方代理的刮刮器，例如如下网址API
https://github.com/zce/douban-api-proxy

**Comment by zlhdd108** [comment]
还可以考虑自行添加apikey，目前网上有些可以搜索到的apikey，可以自行替换

**Comment by taxigps** [comment]
最好的还是默认的themoviedb

**Comment by einverne** [comment]
themoviedb 甚至开放了 meta 信息编辑，可以去贡献一下。

**Comment by zhangsean** [comment]
themoviedb 电影信息确实比较全，可惜信息都是英文，评分也不准确。

**Comment by anticlockwise** [comment]
@zhangsean 可以首选中文的，评分嘛，的确审美不一样。。。
