### ISSUE TITLE
射手字幕插件无法正常下载字幕

### ISSUE THREAD

**Issue by rj8928** [taxigps/xbmc-addons-chinese#241]
第一次打开时能正常搜索并显示选择字幕，但是无法下载，会一直卡着。之后就搜索不了了，别的字幕插件也不能搜索了。（不使用assrt时别的字幕插件能正常使用）退出kodi会无响应。kodi18.4，win10系统。

**Comment by msydh** [comment]
我也是这样

**Comment by yang900313** [comment]
现在好用的中文字幕和菜单插件有哪个呢。
ios 18.5怎么安装的， 看不到本地手机文件。
请教一下
