### ISSUE TITLE
字幕插件在最新的kodi 19测试版上，报xbmc.python 2.1.0依赖不满足。

### ISSUE THREAD

**Issue by ccxp** [taxigps/xbmc-addons-chinese#249]
如题

**Comment by taxigps** [comment]
更新了专门用于Kodi 19的中文插件库及相应支持Kodi 19的字幕插件。请下载升级中文插件库https://github.com/taxigps/xbmc-addons-chinese/raw/matrix/repo/repository.xbmc-addons-chinese/repository.xbmc-addons-chinese-2.0.0.zip

**Comment by ccxp** [comment]
https://github.com/ccxp/xbmc-addons-chinese
说起来那三个字幕插件我自己也改过了^^

**Comment by fsjack** [comment]
最新的kodi matrix alpha又不行了
