### ISSUE TITLE
LeTV Script Failed

### ISSUE THREAD

**Issue by mixboser** [taxigps/xbmc-addons-chinese#25]
There is Script failed on the LeTV plugin.  Here is the error from the log.
17:31:23 T:38112   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: invalid literal for int() with base 10: ''
                                            Traceback (most recent call last):
                                              File "C:\Users\mix\AppData\Roaming\Kodi\addons\plugin.video.letv\default.py", line 1068, in <module>
                                                progListMovie(name, url, cat, filtrs, page, listpage)
                                              File "C:\Users\mix\AppData\Roaming\Kodi\addons\plugin.video.letv\default.py", line 326, in progListMovie
                                                p_dx = int(vlist[i]['duration'])
                                            ValueError: invalid literal for int() with base 10: ''
                                            -->End of Python script error report<--
17:31:23 T:38248   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.letv/?cat=%e5%85%a8%e9%83%a8&filtrs=%26o%3d9&listpage&mode=1&name=%e7%94%b5%e5%bd%b1&page=1&url=http%3a%2f%2flist.letv.com%2flistn%2fc1_t-1_a-1_y-1_s1_lg-1_ph-1_md_o9_d1_p.html
17:31:23 T:38248   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.letv/?cat=%e5%85%a8%e9%83%a8&filtrs=%26o%3d9&listpage&mode=1&name=%e7%94%b5%e5%bd%b1&page=1&url=http%3a%2f%2flist.letv.com%2flistn%2fc1_t-1_a-1_y-1_s1_lg-1_ph-1_md_o9_d1_p.html) failed

**Comment by osfans** [comment]
可以解决，给出视频列表，但是播放时出现“无法播放：多次未匹配到视频文件，请选择其它视频”

**Comment by osfans** [comment]
@mixboser 替换这个文件看看。
"C:\Users\mix\AppData\Roaming\Kodi\addons\plugin.video.letv\default.py"换成：

https://raw.githubusercontent.com/taxigps/xbmc-addons-chinese/master/plugin.video.letv/default.py

**Comment by mixboser** [comment]
Thanks, osfans.

With the new default.py, I can get the play list.  But get “无法播放：多次未匹配到视频文件，请选择其它视频” when playing the video.

**Comment by osfans** [comment]
似乎是http://www.flvcd.com/url.php中letv的鏈接出問題了。

**Comment by cmeng-git** [comment]
I have been trying for the last few weekends to fix the flvcd video link fetch error; however not successfully. Also I was facing major hurdle is that most for the video viewing are blocked outside China due to copyright making debug very difficult. I am not sure if this video blocking has led to the flvcd video link fetch problem. The same flvcd video link fetch is also used in yinyuetai video plugin, and is still working today.

I tried also using www.flvdown.com but also lead to noway. I am now stuck.

**Comment by cmeng-git** [comment]
Please try the latest release version 1.4.2

**Comment by pareshnilewar** [comment]
Hello Friends.. I am from India and i am stucked in a big problem. I have LeEco LETV Super3 X55. After flashed wrong bin file error shows reboot the system and when i reboot the tv its not turning on. Somewhere i found that trigger file LETV_USB_SCRIPT_928 can make it alive again with Original bin file in same u Disk.. Please help me to turn my TV on again. Send me live link for LETV_USB_SCRIPT_928 and original full bin file for LeEco LETV Super3 X55..

Thank You.....
