### ISSUE TITLE
Subhd Failed to download subtitles

### ISSUE THREAD

**Issue by elonj** [taxigps/xbmc-addons-chinese#251]
Kodi 18.6上使用subhd 1.0.22出现Failed to download subtitles

说说自己的发现：
1. SUBHD_BASE 改成 'https://subhd.tv' 的话，好像需要图片验证的机率小。至少在chrome上，打开https://subhd.tv 下载字幕很少需要验证。而subhd.la经常需要验证。
2. SUBHD网站的dtoken现在好像改成了dtoken1
3. 完成上述修改之后，KODI运行SUBHD下载字幕，出现提示“请刷新页面重新下载”和“Failed to download subtitles”

不知道该怎么解决？请帮帮忙，谢谢！

**Comment by 4ft35t** [comment]
验证码问题无法处理，暂时发现字幕预览无需验证码。虽然一次只能下载一个文件，但是足够用。
https://github.com/taxigps/xbmc-addons-chinese/pull/256

**Comment by elonj** [comment]
试了一下，用好几个文件试了好几次，选择字幕时，列表一直为空。不知道是什么原因

**Comment by elonj** [comment]
> 验证码问题无法处理，暂时发现字幕预览无需验证码。虽然一次只能下载一个文件，但是足够用。
> #256

试了一下，用好几个文件试了好几次，选择字幕时，列表一直为空。不知道是什么原因

**Comment by 4ft35t** [comment]
> > 验证码问题无法处理，暂时发现字幕预览无需验证码。虽然一次只能下载一个文件，但是足够用。
> > #256
> 
> 试了一下，用好几个文件试了好几次，选择字幕时，列表一直为空。不知道是什么原因

视频的文件名发一下

**Comment by elonj** [comment]
Westworld.S03E01, The.Crown.S03E01
能搜到字幕，但是选择字幕时是空的。试了https，还是空的。你那边试没问题吗？

**Comment by taxigps** [comment]
有此字幕没有预览，例子http://subhd.tv/a/384665

**Comment by 4ft35t** [comment]
- Westworld.S03E01 5个字幕版本，测试都没问题
- The.Crown.S03E01 2个字幕版本都 __没有提供预览__

__预览是新功能，目前只提供给了新上传的字幕__。不知道老的字幕字是否会后续会增加预览支持。
一些其它测试
- 调整接口用的 Westworld.S03E07 做测试，没有问题
- 网站首页的`热门字幕`和`最新字幕`都有预览

从预览接口提取字幕，只是对有验证码完全不能使用情况的一种缓解手段，在网站给所有字幕提供预览前，无法支持所有字幕。
结合现实情况，伪射手 http://assrt.net/ 的字幕也在更新，只是会比 subhd 晚几个小时，两个插件配合使用
- service.subtitles.makedie 做主力从 assrt.net 下载，优先使用
- 当天更新的新剧用如果  assrt.net 没结果，就用 subhd 从预览接口下载

后续可以考虑把两个插件按上面的逻辑做整合，伪射手没结果时从 subhd 搜索作为补充。

**Comment by elonj** [comment]
听起来不错，希望尽快commit可以更新

**Comment by 4ft35t** [comment]
整合也有些问题，以 Westworld s03 为例：
- s03e06 及之前内容，subhd 有的字幕 assrt 都有
- s03e07 目前 assrt  只有人人影视版本字幕，发布时间比 subhd 晚几个小时
- s03e07 在 subhd 的其它版本，不知道好久才能发布到 assrt

所以还是两个插件都装吧，手动切换。

**Comment by elonj** [comment]
嗯嗯，所有的字幕插件都装了，只是有时候没有一个能下载字幕成功。希望更新之后好一点

**Comment by taxigps** [comment]
字幕选择列表只截取后50个字符，会不会有的字幕版本信息不全，不利于选择下载。

**Comment by taxigps** [comment]
已升级1.0.23，感谢4ft35t
