### ISSUE TITLE
Douban TV scraper

### ISSUE THREAD

**Issue by janplus** [taxigps/xbmc-addons-chinese#26]
我在你写的豆瓣电影刮削器的基础上写了一个电视剧的，可以获取TV信息，由于豆瓣API问题目前还不能获取Episode信息。

项目在 https://github.com/janplus/kodi-doubantv-scraper
Zip文件 https://github.com/janplus/kodi-doubantv-scraper/archive/rc_0.0.1.zip

**Comment by osfans** [comment]
taxi老大有的插件不在这个库里，不知是因为不支持了，还是提交到其他库了。

**Comment by taxigps** [comment]
没有分集信息意义不大吧。

**Comment by janplus** [comment]
方便电视剧入库，可以照分类、年份、演员等查找，有需要就拿去用吧，放在这是方便其他人能找到。

**Comment by taxigps** [comment]
没有分集信息只能在文件模式使用，在剧集模式没有可播放项。如能获取分集信息就真正实用了。不过还要感谢分享。

**Comment by janplus** [comment]
你是对的，我更新了插件，直接从HTML页面获取分集信息。

项目仍在 https://github.com/janplus/kodi-doubantv-scraper
zip文件︰https://github.com/janplus/kodi-doubantv-scraper/archive/rc_1.0.0.zip

**Comment by taxigps** [comment]
如需加入插件库，提交一个pull request吧。

**Comment by taxigps** [comment]
已加入：https://github.com/taxigps/xbmc-addons-chinese/commit/49f7c8d35d6c19d8f4c2c368e2c50f7eb689948a

**Comment by msleong** [comment]
taxigps大大, 我用ANDROID KODI 17.3 插件豆瓣电影刮削器, 不给安装, 可帮忙查看吗? 是不是不能用了?
谢你!!

**Comment by jindaxia** [comment]
说出你的操作步骤，如何叫“不给安装”？

**Comment by msleong** [comment]
本地电影1)添加视频，2)编辑源，3)该目录包含选：电影，4)选择信息提供者：THE MOVIE DATABASE(没问题), 5)获取更多下载：豆瓣电影刮削器，下载。
后会出一个提示，(The dependency on metadata.common.movieposterdb.com version 1.0 could not be satisfied.)
不给下载。。。请查。。谢

**Comment by msleong** [comment]
本机器盒子，android 5.1 小米盒子增强版(白色)

**Comment by jindaxia** [comment]
#169 已确认，开新的Issue
