### ISSUE TITLE
zimuku插件失效

### ISSUE THREAD

**Issue by texlahoma** [taxigps/xbmc-addons-chinese#261]
一直很好用 最近突然无法搜索到任何字幕 插件版本1.1.3 kodi版本18.7

**Comment by NV3S** [comment]
是的，同时我这里，subhd能够搜到但是下载失败。

**Comment by YK-Samgo** [comment]
我修正了字幕库的下载问题，同时提升了可靠性。
换用别的库理论上支持了好多压缩格式，但是实际测试下来会有问题，如果那些包里有不认识的编码（比如，出现中文），那么kodi的库就无法解包，甚至会奔溃。。。兄弟们说该不该为了那点压缩格式，留这个隐患？
https://github.com/YK-Samgo/xbmc-addons-chinese/releases/tag/v1.1.4

**Comment by taxigps** [comment]
已升级1.1.4
