### ISSUE TITLE
2020年7月28日 目前的三个字幕的使用情况反馈

### ISSUE THREAD

**Issue by SelfEnough** [taxigps/xbmc-addons-chinese#263]
SubHD能搜索到，但是一点击下载就“下载字幕失败”
zumuku永远搜不到
zimuzu能搜到的都能下载成功

**Comment by fffonion** [comment]
@SelfEnough 伪射手网插件仍然可用

**Comment by 4ft35t** [comment]
搜到不能下载，和搜不到的，留一下视频文件的文件名，我空了看一下。

**Comment by pizzamx** [comment]
升级了 19，只剩射手兼容，但搜不到东西……

**Comment by taxigps** [comment]
@pizzamx 请下载针对19的中文插件库版本

**Comment by pizzamx** [comment]
> @pizzamx 请下载针对19的中文插件库版本

谢谢！
