### ISSUE TITLE
这个项目没人维护了？大多数插件代码几年没有更新，各种报错

### ISSUE THREAD

**Issue by karma-sun** [taxigps/xbmc-addons-chinese#264]
这个项目没人维护了？大多数插件代码几年没有更新，各种报错

**Comment by 4ft35t** [comment]
字幕插件在维护，视频插件放弃吧，视频网站的加载逻辑越来越复杂，精力不够折腾，用手机投屏看。

**Comment by chonghai** [comment]
挺遗憾的，可能是用户数量太少了吧。

**Comment by malimaliao** [comment]
oh ha.

look new~

**Comment by chonghai** [comment]
> oh ha.
> 
> look new~

thanks!

**Comment by chonghai** [comment]
汇报下使用情况，射手的字幕不能用，字幕组的可以。
至于视频插件，可用性不高。
