### ISSUE TITLE
无法连接插件库

### ISSUE THREAD

**Issue by maple-spirit** [taxigps/xbmc-addons-chinese#265]
安装了中文插件库zip从库安装显示无法连接插件库

**Comment by ddyllen-z** [comment]
我也是，无法连接，估计是被墙了。

**Comment by v2cn** [comment]
的确被墙了。解决办法可以参考：
[http://www.kodiplayer.cn/plugins/2835.html](url)

**Comment by MonkeyInWind0** [comment]
+1

**Comment by offbye** [comment]
应该是被墙了  osdm 1.8 kodi 1.9都试过了 连不上

**Comment by malimaliao** [comment]
cure the symptoms, not the disease.

_Because the Chinese plugin library is ultimately connected to github, even if you manually download the plugin library, the final download is still connected to github_
