### ISSUE TITLE
适配kodi19

### ISSUE THREAD

**Issue by YYTB** [taxigps/xbmc-addons-chinese#271]
Kodi19稳定版发布了，请问有迁移到python3适配最新的kodi19的计划吗？

**Comment by taxigps** [comment]
https://github.com/taxigps/xbmc-addons-chinese/raw/matrix/repo/repository.xbmc-addons-chinese/repository.xbmc-addons-chinese-2.0.0.zip

**Comment by YYTB** [comment]
谢谢，我测试一下看，前面直接从老版的插件升级到19无法使用，没有仔细看你们的介绍，抱歉。
