### ISSUE TITLE
zimuku 主域名变更，插件无法使用

### ISSUE THREAD

**Issue by tonyliangli** [taxigps/xbmc-addons-chinese#272]
您好，字幕库的主域名已经变更为zmk.pw，zimuku.la已经无法访问，1.1.5版本zimuku插件也无法使用了。能否更新？谢谢。

**Comment by angelsky11** [comment]
自己把zip包的插件下载下来，然后改一下里面的py程序的url地址，然后手动安装插件就可以了

**Comment by taxigps** [comment]
已升级
