### ISSUE TITLE
CNTV is not working

### ISSUE THREAD

**Issue by tq010or** [taxigps/xbmc-addons-chinese#28]
CNTV is not working again since your update early this year.

**Comment by RunasSudo** [comment]
Can you try with version 2.0.7 from [my repository](https://github.com/RunasSudo/plugin.video.cntv-live/releases/tag/2.0.7) and/or post the error log?

**Comment by tq010or** [comment]
Hi, I downloaded the package from GitHub and tested on my rpi. It prompts unknown error or no hls stream.

**Comment by RunasSudo** [comment]
Which channels are you trying to access?

**Comment by tq010or** [comment]
CCTV 1,5,13

**Comment by RunasSudo** [comment]
Channels 1 and 13 are working on my computer. Can you try on a desktop computer and/or post the contents of the xbmc.log/kodi.log file?

**Comment by RunasSudo** [comment]
CNTV servers have undergone a number of changes over the past few weeks. If the plugin (now version 2.0.8) is not working, please post the error log.

**Comment by oscarchd** [comment]
hello runassudo

what i'm interested is cctv5, cctv5+, and these are the error logs

10:25:25 T:10020  NOTICE: Thread LanguageInvoker start, auto delete: false
10:25:25 T:10020  NOTICE: -->Python Interpreter Initialized<--
10:25:25 T:10020 WARNING: Attempt to use invalid handle -1

10:25:30 T:13008  NOTICE: Thread JobWorker start, auto delete: true

10:27:06 T:13984  NOTICE: Previous line repeats 1 times.
10:27:06 T:13984  NOTICE: Thread LanguageInvoker start, auto delete: false
10:27:07 T:13984  NOTICE: -->Python Interpreter Initialized<--
10:27:07 T:13984 WARNING: Attempt to use invalid handle -1

**Comment by sczhengyabin** [comment]
Strange，CNTV Live works well on win10 UWP kodi v17.0，but not works well on RPi3 with either Raspbian(kodi v15.2) or OSMC (kodi v16.1)
