### ISSUE TITLE
伪射手插件不支持kodi19

### ISSUE THREAD

**Issue by unyielding2013** [taxigps/xbmc-addons-chinese#283]
伪射手字幕库比射手字幕库好多了，为什么没有人维护了？

**Comment by lanyucomputer** [comment]
同感，但没有可以用的，有没有有高手改一下

**Comment by taxigps** [comment]
我找时间升级下伪射手

**Comment by taxigps** [comment]
已将支持Kodi 19的伪射手字幕插件service.subtitles.assrt加入插件库

**Comment by lanyucomputer** [comment]
感谢大佬默默付出维护，确实可以用了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月3日(星期六) 凌晨0:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [taxigps/xbmc-addons-chinese] 伪射手插件不支持kodi19 (Issue #283)





 
已将支持Kodi 19的伪射手字幕插件service.subtitles.assrt加入插件库
