### ISSUE TITLE
zimuku插件似乎失效了

### ISSUE THREAD

**Issue by wztemp1234** [taxigps/xbmc-addons-chinese#284]
上周末开始出现的问题，
使用ip尝试过美国和加拿大
系统尝试过windows 10 19044和android 10的tv box
kodi版本19.3和19.4

pizzamx的zimukux和您的zimuku都显示找不到字幕。

没有错误信息, 错误log是空的

谢谢谢谢！

**Comment by wztemp1234** [comment]
我现在的暂时的fix
1，去kodi官方库下载opensubtitle
2，去opensubtitle注册个用户名密码，在kodi opensubtitle安装页面输入用户名密码
3，去kodi系统设置 - 播放器 - 语言
3.1, 字幕 - 首选字母语言 - chinese
3.2, 下载服务 - 下载字幕语言 - chinese （注意这里可以多选，只要中文的话不要多选）

这样就用opensubtitle，自动筛选中文了。

opensubtitle明显不如zimuku，将就着用吧。。。
this was fun while it lasted. 未来要中文字幕可能只能买个singapore的ip然后用netflix了

**Comment by taxigps** [comment]
升级到2.0.5

**Comment by haso2007** [comment]
持高清基本都是要自已挂字幕，如果这个zimuku插件能用那就真太好了，但我试了不好用。2.05版现在能用了吗。话说字幕库的地址也老变来变去的。一会pw,一会org.

**Comment by taxigps** [comment]
目前使用正常。

**Comment by lanyucomputer** [comment]
> 3.2, 下载服务 - 下载字幕语言 - chinese （注意这里可以多选，只要中文的话不要多选）

这样设置后，依然搜不到中文字幕
