### ISSUE TITLE
哆啦搜索希望再加入几个源

### ISSUE THREAD

**Issue by Shimada666** [taxigps/xbmc-addons-chinese#293]
感谢作者提供插件，插件很好用。反馈一些问题，目前哆啦搜索存在搜到了打不开、打开了不清晰、看tvb剧仅有国语配音等问题，希望能多加入几个源以供选择更多视频影片

**Comment by RebelYoung** [comment]
我啥都搜不了，直接失败，请问是不是有什么设置要改

**Comment by malimaliao** [comment]
请在插件设置中开启云搜索引擎，那么可以获得基于云的多个搜索引擎。
另外，内置的搜索引擎也是允许修改为自己的，那么如何找到适合自己的搜索引擎接口呢？

你可以在google或者yandex、bing搜索”资源采集网“、”资源帮助中心“，打开她们的采集帮助里面，关于json api接口。
其中接口地址格式参照教程：https://github.com/malimaliao/kodi/tree/matrix/plugin.video.duolasousuo

**Comment by malimaliao** [comment]
> 我啥都搜不了，直接失败，请问是不是有什么设置要改

在插件设置中开启云搜索引擎，那么可以获得基于云的多个搜索引擎.

**Comment by malimaliao** [comment]
> 感谢作者提供插件，插件很好用。反馈一些问题，目前哆啦搜索存在搜到了打不开、打开了不清晰、看tvb剧仅有国语配音等问题，希望能多加入几个源以供选择更多视频影片

在插件设置中开启云搜索引擎，那么可以获得基于云的多个搜索引擎. 另外插件即将更新到1.5.0版本，不仅支持搜索，还支持频道浏览。
