### ISSUE TITLE
kodi 14.1 更新 chinese.keyboard 后大面积插件不能用了

### ISSUE THREAD

**Issue by chaichunyang** [taxigps/xbmc-addons-chinese#31]
kodi 14.1 更新 chinese.keyboard 后大面积插件不能用了

**Comment by osfans** [comment]
我這沒得問題。chinese.keyboard v2.0.4

**Comment by taxigps** [comment]
中文输入插件测试没有问题。没有具体问题表述，没有log文件，无法确定是什么问题。

**Comment by wstephen** [comment]
taxigps
因為也是同樣的拼音模式，可以幫幫忙做一個廣東話拼音鍵盤嗎？我有完整的字碼表。如果您願意的話，請把需要的空白字庫表格發給我。

謝謝您的考慮。
wstephen

**Comment by jindaxia** [comment]
@wstephen  KODI 16之后可以自己添加键盘。

**Comment by taxigps** [comment]
@jindaxia 目前码表是内建在Kodi源程序中的，不能简单通过修改配置文件随意增加。
