### ISSUE TITLE
乐视，pps搜索功能无法使用

### ISSUE THREAD

**Issue by imzf** [taxigps/xbmc-addons-chinese#34]
kodi 15.0
19:39:20 T:140626836154112   ERROR: 'lxml.etree._ExceptionContext._store_raised'
19:39:20 T:140626836154112   ERROR:  ignored
19:39:20 T:140626836154112   ERROR: Exception
19:39:20 T:140626836154112   ERROR: TypeError
19:39:20 T:140626836154112   ERROR: :
19:39:20 T:140626836154112   ERROR: "'NoneType' object is not callable"
19:39:20 T:140626836154112   ERROR:  in
19:39:20 T:140626836154112   ERROR: 'lxml.etree._ExceptionContext._store_raised'
19:39:20 T:140626836154112   ERROR:  ignored
19:39:20 T:140626836154112   ERROR: Exception
19:39:20 T:140626836154112   ERROR: TypeError
19:39:20 T:140626836154112   ERROR: :
19:39:20 T:140626836154112   ERROR: "'NoneType' object is not callable"
19:39:20 T:140626836154112   ERROR:  in
19:39:20 T:140626836154112   ERROR: 'lxml.etree._ExceptionContext._store_raised'
19:39:20 T:140626836154112   ERROR:  ignored
19:39:20 T:140626836154112   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'text'
                                            Traceback (most recent call last):
                                              File "/home/test/.kodi/addons/plugin.video.ppstream/default.py", line 1572, in <module>
                                                searchPPS()
                                              File "/home/test/.kodi/addons/plugin.video.ppstream/default.py", line 782, in searchPPS
                                                keyboard = Apps('','请输入搜索内容')
                                              File "/home/test/.kodi/addons/script.module.keyboard.chinese/lib/ChineseKeyboard.py", line 402, in __init__
                                                self.initWindowXML()
                                              File "/home/test/.kodi/addons/script.module.keyboard.chinese/lib/ChineseKeyboard.py", line 448, in initWindowXML
                                                px = int(it.posx.text)
                                            AttributeError: 'NoneType' object has no attribute 'text'
                                            -->End of Python script error report<--
19:39:20 T:140628190537664   ERROR: GetDirectory - Error getting plugin://plugin.video.ppstream/?mode=31
19:39:20 T:140628190537664   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.ppstream/?mode=31) failed
19:39:20 T:140626836154112  NOTICE: Thread LanguageInvoker start, auto delete: false

**Comment by NoAnyLove** [comment]
我这里乐视的搜索无法使用，搜索结果为空，日志里面出现ERROR报错。PPS插件没有用过。

**Comment by cmeng-git** [comment]
I believe ppstream site has terminated and has made all its content links to http://www.iqiyi.com/.
I will observe for a while, if need to, I will have to remove the ppstream plugin for Kodi.

**Comment by cmeng-git** [comment]
Just released letv version 1.7.9 for proper video playback. Found that letv site has actually fragmented the video into very short duration clips. So far I am unaware kodi supports playlist next item pre-load. So the viewing is not that smooth.

pps status remains unchanged.
