### ISSUE TITLE
乐视已经失效

### ISSUE THREAD

**Issue by mcjoeng** [taxigps/xbmc-addons-chinese#39]
本来就没几个好用的国内视频插件，乐视也失效了。很明显这几年除了视频网站加强防视频解析，网友也不大愿意做中文视频网站的插件了。热情逐渐消退。

**Comment by fanshaohua-fan** [comment]
仿照音悦台修改了一下，使用flvcd来解析视频源地址；
但是不能播放会员视频；
不过也在常理之中，免费播放会员视频，只要letv不傻，总会被封掉的；
