### ISSUE TITLE
Chinese Keyboard失效导致大量插件无法安装

### ISSUE THREAD

**Issue by NoAnyLove** [taxigps/xbmc-addons-chinese#42]
使用的OSMC 2015.06-1，系统有安装Python 2.7.9。Chinese Keyboard被表示为不兼容，显示“依耐性为找到。请联系插件作者”。然后导致大量的插件都不能安装，包括搜狐视频、B站、一听、酷我、以及所有的字幕插件、等等。

**Comment by NoAnyLove** [comment]
好吧，也许不是Chinese Keyboard的问题，导入`xbmc.python`和`script.module.xbmcswift2`的Bilibili插件显示不兼容；导入`xbmc.python`和`script.module.beautifulsoup4`等插件都显示不兼容。但是我已经在Kodi Add-on repository插件库中安装了xbmcswift2、beautifulsoup和beautifulsoup4，依然显示不兼容，不知道为什么了。。。

**Comment by taxigps** [comment]
删除userdata/Addonsxx.db重启kodi让它重建数据库试试，可能是网络问题造成插件库信息不完整。

**Comment by NoAnyLove** [comment]
干掉了 `.kodi/userdata/Database/Addons16.db` ，重启之后果然好用了。非常感谢
