### ISSUE TITLE
不知道在哪里说，想请教关于droidsansfallback和dejavu sans丢失'不'等字问题

### ISSUE THREAD

**Issue by uboats** [taxigps/xbmc-addons-chinese#43]
看到您5年前的回复：
http://trac.kodi.tv/ticket/6397#comment:25
然后想问您最后怎么解决的，那个unicode的fallback哪里能看出区别来？
我和您脚本一样。现在找到的droidsans字体是从https://github.com/android/platform_frameworks_base/tree/master/data/fonts 下的fallback和fallbackfull。但是合并的是dejavu lgc sans (dejavu sans网站可以找到)。
结果两个做出来的都丢失那几个字。我是把dejavu sans所有的斜体，紧凑，粗体等都合并了。

想问问您的解决方式。我在github里的账号是uboats。是否方便给您的邮件地址？

**Comment by taxigps** [comment]
在ticket里的回复已很清楚了，没有其它可补充。
