### ISSUE TITLE
优酷视频插件，只能解析40分钟以下的视频

### ISSUE THREAD

**Issue by NoAnyLove** [taxigps/xbmc-addons-chinese#44]
看日志，是以m3u8列表解析的，例如下面这个日志：

```
09:21:01 T:13060  NOTICE: DVDPlayer: Opening: http://pl.youku.com/playlist/m3u8?vid=233777711&ts=1437441661&ctype=12&token=9099&keyframe=1&sid=943744166239512584a36&ev=1&type=hd2&ep=eyaXHU2JV8gG5yDWjT8bYiTmJXQJXPwJ9RiChtVjAdQtSOG2&oip=3063342984
```

但这个m3u8文件只包含前40分钟的视频（或者顶多40分零几秒）。测试了其他电视剧和电影，超过40分钟的视频的长度都只会显示40分钟（或者40分零几秒），绝对不会出现41分钟以上的视频。

**Comment by NoAnyLove** [comment]
应该是优酷提供的m3u8文件的问题，已经在OSMC和PC上装的Kodi上试过，都是同样的问题。

此外，我找了一部时间远远超过40分钟的视频（电影赌城风云2），计算了它的m3u8文件中所有#EXTINF的时间和，只有2403秒，也就是40分钟零3秒。

**Comment by taxigps** [comment]
升级到2.2.3（https://github.com/taxigps/xbmc-addons-chinese/commit/0efbd50c91bdc075cf84466ff561738530de8952），默认不使用m3u8播放。
