### ISSUE TITLE
Chinese Keyboard 失效？

### ISSUE THREAD

**Issue by fanshaohua-fan** [taxigps/xbmc-addons-chinese#46]
错误日志如下：

20:11:50 T:140632160974592  NOTICE: getHttpData: http://pv.sohu.com/suv/?t?=1438452710866725_1920_1080?r?=
20:12:11 T:140632160974592  NOTICE: Thread BackgroundLoader start, auto delete: false
20:12:22 T:140632588805888  NOTICE: Thread LanguageInvoker start, auto delete: false
20:12:22 T:140632588805888  NOTICE: -->Python Interpreter Initialized<--
20:12:22 T:140632588805888   ERROR: Exception
20:12:22 T:140632588805888   ERROR: TypeError
20:12:22 T:140632588805888   ERROR: :
20:12:22 T:140632588805888   ERROR: "'NoneType' object is not callable"
20:12:22 T:140632588805888   ERROR:  in
20:12:22 T:140632588805888   ERROR: 'lxml.etree._ExceptionContext._store_raised'
20:12:22 T:140632588805888   ERROR:  ignored
20:12:22 T:140632588805888   ERROR: Exception
20:12:22 T:140632588805888   ERROR: TypeError
20:12:22 T:140632588805888   ERROR: :
20:12:22 T:140632588805888   ERROR: "'NoneType' object is not callable"
20:12:22 T:140632588805888   ERROR:  in
20:12:22 T:140632588805888   ERROR: 'lxml.etree._ExceptionContext._store_raised'
20:12:22 T:140632588805888   ERROR:  ignored
20:12:22 T:140632588805888   ERROR: Exception
20:12:22 T:140632588805888   ERROR: TypeError
20:12:22 T:140632588805888   ERROR: :
20:12:22 T:140632588805888   ERROR: "'NoneType' object is not callable"
20:12:22 T:140632588805888   ERROR:  in
20:12:22 T:140632588805888   ERROR: 'lxml.etree._ExceptionContext._store_raised'
20:12:22 T:140632588805888   ERROR:  ignored
20:12:22 T:140632588805888   ERROR: Exception
20:12:22 T:140632588805888   ERROR: TypeError
20:12:22 T:140632588805888   ERROR: :
20:12:22 T:140632588805888   ERROR: "'NoneType' object is not callable"
20:12:22 T:140632588805888   ERROR:  in
20:12:22 T:140632588805888   ERROR: 'lxml.etree._ExceptionContext._store_raised'
20:12:22 T:140632588805888   ERROR:  ignored
20:12:24 T:140633791784896   ERROR: file : XML file doesnt contain <window>
20:12:24 T:140632588805888   ERROR: EXCEPTION: Non-Existent Control 48
20:12:24 T:140632588805888   ERROR: EXCEPTION: Non-Existent Control 309
20:12:24 T:140632588805888   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: Non-Existent Control 309
                                            Traceback (most recent call last):
                                              File "/home/fan/.kodi/addons/script.module.keyboard.chinese/lib/ChineseKeyboard.py", line 108, in onInit
                                                self.getControl(CTL_BUTTON_LAYOUT).setLabel("")
                                            RuntimeError: Non-Existent Control 309
                                            -->End of Python script error report<--

**Comment by taxigps** [comment]
见https://github.com/taxigps/xbmc-addons-chinese/issues/48
