### ISSUE TITLE
Get some error While using SUBHD

### ISSUE THREAD

**Issue by jackwangshanghai** [taxigps/xbmc-addons-chinese#47]
The first time I use sub hd everything seem correct, download extract zip got the sub I wanted. But after that I cannot open any other subs. When I try to download another subs using sub hd add-on, it will download, but always unzip the zip file which is the first time when I use this add-on. So whatever I do this add-on only open the first zip file. I try to reinstall this add on, not work.
The KODI is install on Android TV using Android 5.1

**Comment by taxigps** [comment]
It's not a bug of subhd add-on. the problem is we can't delete the temp file under some android system use python function in kodi.

**Comment by jackwangshanghai** [comment]
Sound like there is no solution. But I wonder why the shooter(fake) do not have same problem. It won't open the wrong zip file(file name Guardian of Galaxy). And how can I delete the file by myself,seemed like I need to clean it by myself otherwise the KODI will become bigger and bigger. Dose different add-on use different storage area. Anyway thanks~.

**Comment by taxigps** [comment]
fixed.
