### ISSUE TITLE
script.module.keyboard.chinese 错误

### ISSUE THREAD

**Issue by chaichunyang** [taxigps/xbmc-addons-chinese#48]
我使用xbmc13.2百度云插件进行账户添加时后台显示错误，请帮忙解决。
环境，ubuntu 14.04，xbmc 13.2
日志信息：
23:50:00 T:139987762030336  NOTICE: Thread LanguageInvoker start, auto delete: false
23:50:00 T:139987762030336  NOTICE: -->Python Interpreter Initialized<--
23:50:00 T:139987762030336  NOTICE: [xbmcswift2] Request for "/add_user/" matches rule for function "add_user"
23:50:01 T:139988837767104   ERROR: file : XML file doesnt contain <window>
23:50:01 T:139987762030336   ERROR: EXCEPTION: Non-Existent Control 48
23:50:01 T:139987762030336   ERROR: EXCEPTION: Non-Existent Control 309
23:50:01 T:139987762030336   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: Non-Existent Control 309
                                            Traceback (most recent call last):
                                              File "/home/cc/.xbmc/addons/script.module.keyboard.chinese/lib/ChineseKeyboard.py", line 108, in onInit
                                                self.getControl(CTL_BUTTON_LAYOUT).setLabel("")
                                            RuntimeError: Non-Existent Control 309
                                            -->End of Python script error report<--

**Comment by taxigps** [comment]
你用的是官方默认皮肤吗？

**Comment by chaichunyang** [comment]
是默认皮肤

**Comment by mashihua** [comment]
tvOS 上也出现这个问题：

20:15:36 T:6149156864   DEBUG: CPythonInvoker(48, /var/mobile/Containers/Data/Application/5A5B28B9-3FB4-484B-BF5F-5B35A6BCE33C/Library/Caches/home/addons/plugin.video.myclouds/myclouds.py): entering source directory /var/mobile/Containers/Data/Application/5A5B28B9-3FB4-484B-BF5F-5B35A6BCE33C/Library/Caches/home/addons/plugin.video.myclouds
20:15:36 T:6149156864   DEBUG: CPythonInvoker(48, /var/mobile/Containers/Data/Application/5A5B28B9-3FB4-484B-BF5F-5B35A6BCE33C/Library/Caches/home/addons/plugin.video.myclouds/myclouds.py): instantiating addon using automatically obtained id of "plugin.video.myclouds" dependent on version 0.0.0 of the xbmc.python api
20:15:37 T:6143422464   DEBUG: ------ Window Init (/var/mobile/Containers/Data/Application/5A5B28B9-3FB4-484B-BF5F-5B35A6BCE33C/Library/Caches/home/userdata/addon_data/plugin.video.myclouds/resources/skins/skin.confluence/720p/DialogKeyboardChinese.xml) ------
20:15:37 T:6143422464    INFO: Loading skin file: /var/mobile/Containers/Data/Application/5A5B28B9-3FB4-484B-BF5F-5B35A6BCE33C/Library/Caches/home/userdata/addon_data/plugin.video.myclouds/resources/skins/skin.confluence/720p/DialogKeyboardChinese.xml, load type: LOAD_ON_GUI_INIT
20:15:37 T:6143422464 WARNING: Skin has invalid include:
20:15:37 T:6143422464   DEBUG: Load /var/mobile/Containers/Data/Application/5A5B28B9-3FB4-484B-BF5F-5B35A6BCE33C/Library/Caches/home/userdata/addon_data/plugin.video.myclouds/resources/skins/skin.confluence/720p/DialogKeyboardChinese.xml: 45.13ms
20:15:37 T:6143422464   DEBUG: Alloc resources: 49.88ms  (45.55 ms skin load)
20:15:37 T:6143422464   DEBUG: CGUIMediaWindow::GetDirectory ()
20:15:37 T:6143422464   DEBUG:   ParentPath = []
20:15:37 T:6149156864   ERROR: EXCEPTION: Non-Existent Control 48
20:15:37 T:6149156864   ERROR: EXCEPTION: Non-Existent Control 311
20:15:37 T:6149156864   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: Non-Existent Control 311
                                            Traceback (most recent call last):
                                              File "/var/mobile/Containers/Data/Application/5A5B28B9-3FB4-484B-BF5F-5B35A6BCE33C/Library/Caches/home/addons/plugin.video.myclouds/lib/ChineseKeyboard.py", line 113, in onInit
                                                self.getControl(CTL_LABEL_HEADING).setLabel(self.strHeading)
                                            RuntimeError: Non-Existent Control 311
                                            -->End of Python script error report<--
20:15:37 T:6148009984    INFO: CPythonInvoker(47, /var/mobile/Containers/Data/Application/5A5B28B9-3FB4-484B-BF5F-5B35A6BCE33C/Library/Caches/home/addons/plugin.video.myclouds/myclouds.py): script successfully run



19:52:05 T:6147436544   DEBUG: [xbmcswift2] Adding url rule "/clear_cache/" named "clear_cache" pointing to function "clear_cache"
19:52:05 T:6147436544   DEBUG: [xbmcswift2] Reading pickle storage from disk at "/var/mobile/Containers/Data/Application/5A5B28B9-3FB4-484B-BF5F-5B35A6BCE33C/Library/Caches/home/userdata/addon_data/plugin.video.baiduyun/.storage/.functions"
19:52:05 T:6147436544   DEBUG: [xbmcswift2] Loaded storage ".functions" from disk
19:52:05 T:6147436544   DEBUG: [xbmcswift2] Loaded storage ".functions" from memory
19:52:05 T:6147436544   DEBUG: [xbmcswift2] Adding url rule "/znds/" named "znds.index" pointing to function "index"
19:52:05 T:6147436544   DEBUG: [xbmcswift2] Adding url rule "/znds/gaoqing/" named "znds.gaoqing" pointing to function "gaoqing"
19:52:05 T:6147436544   DEBUG: [xbmcswift2] Adding url rule "/znds/guess/" named "znds.guess" pointing to function "guess"
19:52:05 T:6147436544   DEBUG: [xbmcswift2] Adding url rule "/znds/search/" named "znds.search" pointing to function "search"
19:52:05 T:6147436544   DEBUG: [xbmcswift2] Adding url rule "/znds/list_movies/<link>/" named "znds.list_movies" pointing to function "list_movies"
19:52:05 T:6147436544   DEBUG: [xbmcswift2] Adding url rule "/znds/show_detail/<page_id>/" named "znds.show_detail" pointing to function "show_detail"
19:52:05 T:6147436544   DEBUG: [xbmcswift2] Adding url rule "/znds/bdyun_link/<link>/" named "znds.bdyun_link" pointing to function "bdyun_link"
19:52:05 T:6147436544   DEBUG: [xbmcswift2] Adding url rule "/znds/search_result/<keyword>/" named "znds.search_result" pointing to function "search_result"
19:52:05 T:6147436544   DEBUG: [xbmcswift2] Handling incoming request for /add_user/
19:52:05 T:6147436544  NOTICE: [xbmcswift2] Request for "/add_user/" matches rule for function "add_user"
19:52:06 T:6143422464   DEBUG: ------ Window Init (/var/mobile/Containers/Data/Application/5A5B28B9-3FB4-484B-BF5F-5B35A6BCE33C/Library/Caches/home/userdata/addon_data/script.module.keyboard.chinese/resources/skins/skin.confluence/720p/DialogKeyboardChinese.xml) ------
19:52:06 T:6143422464    INFO: Loading skin file: /var/mobile/Containers/Data/Application/5A5B28B9-3FB4-484B-BF5F-5B35A6BCE33C/Library/Caches/home/userdata/addon_data/script.module.keyboard.chinese/resources/skins/skin.confluence/720p/DialogKeyboardChinese.xml, load type: LOAD_ON_GUI_INIT
19:52:06 T:6143422464 WARNING: Skin has invalid include:
19:52:07 T:6143422464   DEBUG: Load /var/mobile/Containers/Data/Application/5A5B28B9-3FB4-484B-BF5F-5B35A6BCE33C/Library/Caches/home/userdata/addon_data/script.module.keyboard.chinese/resources/skins/skin.confluence/720p/DialogKeyboardChinese.xml: 145.59ms
19:52:07 T:6143422464   DEBUG: Alloc resources: 158.26ms  (146.21 ms skin load)
19:52:07 T:6143422464   DEBUG: CGUIMediaWindow::GetDirectory ()
19:52:07 T:6143422464   DEBUG:   ParentPath = []
19:52:07 T:6147436544   ERROR: EXCEPTION: Non-Existent Control 48
19:52:07 T:6147436544   ERROR: EXCEPTION: Non-Existent Control 311
19:52:07 T:6147436544   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: Non-Existent Control 311
                                            Traceback (most recent call last):
                                              File "/var/mobile/Containers/Data/Application/5A5B28B9-3FB4-484B-BF5F-5B35A6BCE33C/Library/Caches/home/addons/script.module.keyboard.chinese/lib/ChineseKeyboard.py", line 112, in onInit
                                                self.getControl(CTL_LABEL_HEADING).setLabel(self.strHeading)
                                            RuntimeError: Non-Existent Control 311
                                            -->End of Python script error report<--
