### ISSUE TITLE
最近更新的iqiyi插件也挂了

### ISSUE THREAD

**Issue by mcjoeng** [taxigps/xbmc-addons-chinese#56]
现在就剩下Youku插件能用了，但是优酷是分段视频，每段三分钟，用鼠标定位只能定位到当段视频的三分钟内，定位到其他的段就会跳回起点 蛋疼

**Comment by taxigps** [comment]
升级2.1.9

**Comment by taxigps** [comment]
优酷也已升级2.2.3，解决不能定位问题。
