### ISSUE TITLE
[新手问题] 关于开发一个XBMC 插件的整个流程

### ISSUE THREAD

**Issue by zjhiphop** [taxigps/xbmc-addons-chinese#57]
我的开发环境是： Py Charm ＋ Mac OS X

我是一个新手，对以下问题不是很明白：
1. XBMC是一个C＋＋编译好的库，只是对外暴露了python调用的接口？
2. 我在引用 import xbmc, xbmcplugin, xbmcgui, xbmcaddon的时候， 会报模块不存在，那么不知道大家在本地是怎么调试的？是不是一定要部署到kodi平台上去运行才能调试？

**Comment by jindaxia** [comment]
第二个问题，一般来说直接import xbmc 肯定是不存在的，要本地调试呢也是可能的，可以pip install xbmcswift ，用xbmcswift来完成，import的时候要使用 from xbmcswift import xbmc这样

**Comment by cmeng-git** [comment]
Please refer to the following site on how to develop scripts/plugin for kodi:

http://kodi.wiki/view/How-to:Debug_Python_Scripts_with_Eclipse
