### ISSUE TITLE
奇艺，播放10分钟左右返回405

### ISSUE THREAD

**Issue by shuoshi** [taxigps/xbmc-addons-chinese#59]
CCurlFile::Open failed with code 405 

日志里记录到这个，我试了试，不用stack协议，改用playlist，一段段放，也还是405

**Comment by mcjoeng** [comment]
爱奇艺插件，应该是十二分钟，每段是6分钟，播放两段之后就会自动返回列表，我也遇到这个问题

**Comment by taxigps** [comment]
升级到2.2.0
