### ISSUE TITLE
douban 电视剧 无法刮削 英文名的剧集吗？

### ISSUE THREAD

**Issue by iJayscn** [taxigps/xbmc-addons-chinese#63]
例如：

文件名为： Nirvana.in.Fire.Complete.1080p.WEB-DL.H264.AAC

**Comment by taxigps** [comment]
@janplus

**Comment by janplus** [comment]
英文名没有问题，你举的例子中去掉1080p之后的部分即可，即保留Nirvana.in.Fire.Complete。

**Comment by jindaxia** [comment]
@janplus 应该在代码里，先过滤掉1080P这种修饰，在进行搜索

**Comment by taxigps** [comment]
@jindaxia 个人认为这不是刮削器应考虑的问题。用户规范存放剧集的目录名为剧集名即可。

**Comment by jindaxia** [comment]
可是下载下来的片子 一般是这种命名，而且大部分人都不会去改名字的。 xbmc里面不是也有个方法可以获取干净的文件名么

**Comment by taxigps** [comment]
剧集是分目录存放的，用目录名刮削的，并不需要你改文件名。
