### ISSUE TITLE
openelec安装显示插件结构不完整？怎么回事啊？

### ISSUE THREAD

**Issue by pengshp** [taxigps/xbmc-addons-chinese#68]
我从zip文件安装xbmc-addons-chinese时显示插件结构不完整怎么回事啊？我的是pi2,系统是openelec6.0,没影响吧

**Comment by taxigps** [comment]
估计你下载了错误的压缩包。应该是这个https://github.com/taxigps/xbmc-addons-chinese/raw/master/repo/repository.xbmc-addons-chinese/repository.xbmc-addons-chinese-1.2.0.zip
