### ISSUE TITLE
YouKu TV causes Kodi to hang on playback  

### ISSUE THREAD

**Issue by cmeng-git** [taxigps/xbmc-addons-chinese#75]
YouKu TV v1.6.2.
When selecting a movie to playback, it keeps showing "Waiting...." notification. Any key presses to get kodi to abort this mode has no effect. The only way to get out of this mode is to close kodi and restart.

**Comment by taxigps** [comment]
like youku api changed. need author to update again.

**Comment by taxigps** [comment]
update to v1.6.3
