### ISSUE TITLE
doubantv 刮削器无法获取图片

### ISSUE THREAD

**Issue by whmsysu** [taxigps/xbmc-addons-chinese#81]
使用了doubantv刮削器可以成功找到剧集，不过无法获取图片，同时下载的图片的也无法在更改海报一栏更改，没有内容。

**Comment by whmsysu** [comment]
能够看到有远程艺术照片，不过无法获取图片内容，图片的数量获取都是对的。请问有没有知道如何解决？

**Comment by taxigps** [comment]
@janplus

**Comment by janplus** [comment]
豆瓣的API返回值变了，等我抽空改一下

**Comment by taxigps** [comment]
@janplus poster获取问题可参考douban电影刮削器：https://github.com/xbmc/repo-scrapers/pull/23

**Comment by taxigps** [comment]
升级1.2.0
