### ISSUE TITLE
SUBHD 字幕每次可以搜索到，但是打开压缩包都是空的

### ISSUE THREAD

**Issue by fuermosi777** [taxigps/xbmc-addons-chinese#83]
请问是否是bug？如何解决呢？谢谢！

**Comment by palfans** [comment]
相同现象，刚安装这个插件时是好的，就是最近一两周来所有压缩包打开都是空的，然后提示下载失败。

**Comment by taxigps** [comment]
测试正常。是否网络原因？

**Comment by fuermosi777** [comment]
感谢回复。网络正常。补充一下：有一些字幕压缩包解压正常，大概正常/空 ~= 1:5 左右，另外一个插件163sub都是正常的。毫无头绪...

**Comment by palfans** [comment]
网络正常。能搜到字幕，下载的压缩包打开是空的。现在全部用opensubtitles的插件能正常下载字幕。

**Comment by AbrahamSue** [comment]
subhd的rar压缩用了较新的算法，linux上或者xmbc插件的解压缩库解不了。

**Comment by taxigps** [comment]
哪部电影打开为空？请给出电影名及视频文件名，我测试下看是否需要升级kodi的rar解压模块。

**Comment by palfans** [comment]
​比如Sherlock.The.Abominable.Bride，搜索出来的12个结果我全部测试过，都是空压缩包，然后显示下载失败。

Thanks & Regards,


Can ZHU (朱灿)

**Comment by taxigps** [comment]
测试除“字幕被投诉停止下载”的外，下载解压正常。

**Comment by palfans** [comment]
好奇怪，为什么我这里就是不行？

**Comment by fuermosi777** [comment]
@taxigps @palfans  谢谢回复。我这里也不行。基本上所有的电影和电视剧都不行。顺便提一下，我用的是window 10的kodi isengard

**Comment by palfans** [comment]
@fuermosi777 我也是Win10跑的Kodi v15.2

**Comment by fuermosi777** [comment]
@palfans 莫非是因为系统的原因？也许是windows的`XBMC.Extract()`有问题。。晚上我试试小米盒子

**Comment by taxigps** [comment]
win10下测试15.2和16.0rc2基本正常。确实有出现`xbmc.extract()`解压失败，但同一条字幕再试又成功了，开启调试信息后正常了。问题原因暂未明。

**Comment by a-sheng** [comment]
相同现象，刚安装这个插件时是好的，压缩包打开都是空的，然后提示下载失败。

**Comment by besteric** [comment]
我现在也是这个问题，完全无法使用sub hd下载字幕，所有压缩包都是空的，好蛋疼

**Comment by jindaxia** [comment]
@besteric 你至少给一个片名

**Comment by nabule** [comment]
相同现象，刚安装这个插件时是好的，压缩包打开都是空的，然后提示下载失败。

只要有一次下载失败，以后无论下载什么都是失败。重装插件不管用

**Comment by besteric** [comment]
@jindaxia 我这边是所有片源都这样...

**Comment by wystanchen** [comment]
me too啊，不知道为什么，win10，一开始可以，后来换了一款皮肤就不行了，换了estuary，难道跟皮肤也有关系？

**Comment by brettyin** [comment]
我也有类似状况，试了很久，貌似是如果压缩包里直接是字幕文件就没问题，但很多时候压缩包里有另一层压缩包，就会出现空的状况。当然这也符合逻辑，我估计插件只解压一层压缩，没有符合的字幕类型文件，自然就是空了。

**Comment by generalmilk** [comment]
今天研究了一下代码，解决了，看这里
# #120

**Comment by besteric** [comment]
@taxigps 快来合并PR啦，终于解决历史顽疾

**Comment by taxigps** [comment]
已升级插件，感谢@generalmilk
