### ISSUE TITLE
无法进入库，点了没反应

### ISSUE THREAD

**Issue by BrutalOOXX** [taxigps/xbmc-addons-chinese#89]
在 Kodi v15.2 版本中，添加了1.2.0版的插件库，但是点击后没反应。。。。点击其他插件库都能正常进入

**Comment by BrutalOOXX** [comment]
问题解决了，原来是因为没有翻墙。。。。。

**Comment by taxigps** [comment]
不用翻墙也能用的，但确实存在网络问题，刷新下库就好。
