### ISSUE TITLE
多个字幕插件找不到字幕

### ISSUE THREAD

**Issue by 4ft35t** [taxigps/xbmc-addons-chinese#96]
人工输入 
>The.Hunger.Games.Mockingjay.Part.2

在网站上都能找到

|插件|版本|是否找到字幕|备注|
|---|---|---|---|
|subhd|1.0.6|n||
|163sub|1.0.3|y|http://163sub.com/download/f4872259-faa0-4f46-8992-3d7fecedb7a9 压缩包空|
|zimuku|1.0.2|n||

**Comment by mapleshadow** [comment]
顶！的确这样了，需要更新，作者辛苦了

**Comment by generalmilk** [comment]
今天研究了一下代码，解决了，看这里
#120

**Comment by taxigps** [comment]
已升级163sub到1.0.4，感谢@generalmilk
